// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#include "../ui.h"

void ui_login_screen_init(void)
{
    ui_login = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_login, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_login, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 1024);
    lv_obj_set_height(ui_TabView1, 600);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_TabView1, &ui_img_1485140228, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &ui_font_chinese30,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "普通登录");

    lv_obj_set_style_bg_img_src(ui_TabPage1, &ui_img_1485140228, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_TabPage1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 691);
    lv_obj_set_height(ui_Container2, 450);
    lv_obj_set_x(ui_Container2, 2);
    lv_obj_set_y(ui_Container2, -25);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TextArea1, 400);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextArea1, -26);
    lv_obj_set_y(ui_TextArea1, -181);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "输入账号");
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextArea2 = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TextArea2, 400);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextArea2, -26);
    lv_obj_set_y(ui_TextArea2, -90);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "输入密码");
    lv_textarea_set_password_mode(ui_TextArea2, true);
    lv_obj_set_style_text_font(ui_TextArea2, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Buttonsignup1 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Buttonsignup1, 100);
    lv_obj_set_height(ui_Buttonsignup1, 50);
    lv_obj_set_x(ui_Buttonsignup1, -137);
    lv_obj_set_y(ui_Buttonsignup1, -5);
    lv_obj_set_align(ui_Buttonsignup1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonsignup1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonsignup1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelsignup1 = lv_label_create(ui_Buttonsignup1);
    lv_obj_set_width(ui_Labelsignup1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelsignup1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelsignup1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelsignup1, "注册");
    lv_obj_set_style_text_font(ui_Labelsignup1, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonlogin1 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Buttonlogin1, 100);
    lv_obj_set_height(ui_Buttonlogin1, 50);
    lv_obj_set_x(ui_Buttonlogin1, 83);
    lv_obj_set_y(ui_Buttonlogin1, -5);
    lv_obj_set_align(ui_Buttonlogin1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonlogin1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonlogin1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labellogin1 = lv_label_create(ui_Buttonlogin1);
    lv_obj_set_width(ui_Labellogin1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labellogin1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labellogin1, 4);
    lv_obj_set_y(ui_Labellogin1, 0);
    lv_obj_set_align(ui_Labellogin1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labellogin1, "登录");
    lv_obj_set_style_text_font(ui_Labellogin1, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "vip登录");

    ui_Container3 = lv_obj_create(ui_TabPage2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 691);
    lv_obj_set_height(ui_Container3, 450);
    lv_obj_set_x(ui_Container3, 2);
    lv_obj_set_y(ui_Container3, -25);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea3 = lv_textarea_create(ui_Container3);
    lv_obj_set_width(ui_TextArea3, 400);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextArea3, -26);
    lv_obj_set_y(ui_TextArea3, -181);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "输入账号");
    lv_obj_set_style_text_font(ui_TextArea3, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextArea4 = lv_textarea_create(ui_Container3);
    lv_obj_set_width(ui_TextArea4, 400);
    lv_obj_set_height(ui_TextArea4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextArea4, -26);
    lv_obj_set_y(ui_TextArea4, -90);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "输入密码");
    lv_textarea_set_password_mode(ui_TextArea4, true);
    lv_obj_set_style_text_font(ui_TextArea4, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Buttonsignup2 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Buttonsignup2, 100);
    lv_obj_set_height(ui_Buttonsignup2, 50);
    lv_obj_set_x(ui_Buttonsignup2, -137);
    lv_obj_set_y(ui_Buttonsignup2, -5);
    lv_obj_set_align(ui_Buttonsignup2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonsignup2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonsignup2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelsignup2 = lv_label_create(ui_Buttonsignup2);
    lv_obj_set_width(ui_Labelsignup2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelsignup2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelsignup2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelsignup2, "注册");
    lv_obj_set_style_text_font(ui_Labelsignup2, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonlogin2 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Buttonlogin2, 100);
    lv_obj_set_height(ui_Buttonlogin2, 50);
    lv_obj_set_x(ui_Buttonlogin2, 83);
    lv_obj_set_y(ui_Buttonlogin2, -5);
    lv_obj_set_align(ui_Buttonlogin2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonlogin2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonlogin2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labellogin2 = lv_label_create(ui_Buttonlogin2);
    lv_obj_set_width(ui_Labellogin2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labellogin2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labellogin2, 4);
    lv_obj_set_y(ui_Labellogin2, 0);
    lv_obj_set_align(ui_Labellogin2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labellogin2, "登录");
    lv_obj_set_style_text_font(ui_Labellogin2, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "管理员登录");

    ui_Container5 = lv_obj_create(ui_TabPage3);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 691);
    lv_obj_set_height(ui_Container5, 450);
    lv_obj_set_x(ui_Container5, 2);
    lv_obj_set_y(ui_Container5, -25);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea5 = lv_textarea_create(ui_Container5);
    lv_obj_set_width(ui_TextArea5, 400);
    lv_obj_set_height(ui_TextArea5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextArea5, -26);
    lv_obj_set_y(ui_TextArea5, -181);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea5, "输入账号");
    lv_obj_set_style_text_font(ui_TextArea5, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextArea6 = lv_textarea_create(ui_Container5);
    lv_obj_set_width(ui_TextArea6, 400);
    lv_obj_set_height(ui_TextArea6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextArea6, -26);
    lv_obj_set_y(ui_TextArea6, -90);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea6, "输入密码");
    lv_textarea_set_password_mode(ui_TextArea6, true);
    lv_obj_set_style_text_font(ui_TextArea6, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Buttonsignup3 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Buttonsignup3, 100);
    lv_obj_set_height(ui_Buttonsignup3, 50);
    lv_obj_set_x(ui_Buttonsignup3, -137);
    lv_obj_set_y(ui_Buttonsignup3, -5);
    lv_obj_set_align(ui_Buttonsignup3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonsignup3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonsignup3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelsignup3 = lv_label_create(ui_Buttonsignup3);
    lv_obj_set_width(ui_Labelsignup3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelsignup3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelsignup3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelsignup3, "注册");
    lv_obj_set_style_text_font(ui_Labelsignup3, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonlogin3 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Buttonlogin3, 100);
    lv_obj_set_height(ui_Buttonlogin3, 50);
    lv_obj_set_x(ui_Buttonlogin3, 83);
    lv_obj_set_y(ui_Buttonlogin3, -5);
    lv_obj_set_align(ui_Buttonlogin3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonlogin3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonlogin3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labellogin3 = lv_label_create(ui_Buttonlogin3);
    lv_obj_set_width(ui_Labellogin3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labellogin3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labellogin3, 4);
    lv_obj_set_y(ui_Labellogin3, 0);
    lv_obj_set_align(ui_Labellogin3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labellogin3, "登录");
    lv_obj_set_style_text_font(ui_Labellogin3, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_TabView1);
    lv_obj_set_width(ui_Keyboard1, 534);
    lv_obj_set_height(ui_Keyboard1, 259);
    lv_obj_set_x(ui_Keyboard1, -23);
    lv_obj_set_y(ui_Keyboard1, 100);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ImgButton5 = lv_imgbtn_create(ui_TabView1);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButton5, 50);
    lv_obj_set_height(ui_ImgButton5, 30);
    lv_obj_set_x(ui_ImgButton5, -52);
    lv_obj_set_y(ui_ImgButton5, -225);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabPage1, ui_event_TabPage1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea4, ui_event_TextArea4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabPage2, ui_event_TabPage2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea5, ui_event_TextArea5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea6, ui_event_TextArea6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabPage3, ui_event_TabPage3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);

}
