// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: order3

#include "../ui.h"

void ui_order3_screen_init(void)
{
    ui_order3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_order3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_order3, &ui_img_1485140228, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_order3);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 1024);
    lv_obj_set_height(ui_Container8, 400);
    lv_obj_set_x(ui_Container8, 0);
    lv_obj_set_y(ui_Container8, -100);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number30 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number30);
    lv_obj_set_width(ui_number30, 200);
    lv_obj_set_height(ui_number30, 200);
    lv_obj_set_x(ui_number30, -716);
    lv_obj_set_y(ui_number30, -186);
    lv_obj_set_align(ui_number30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber30 = lv_img_create(ui_number30);
    lv_img_set_src(ui_Imagenumber30, &ui_img_1929884129);
    lv_obj_set_width(ui_Imagenumber30, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber30, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber30, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber30, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber30 = lv_obj_create(ui_number30);
    lv_obj_remove_style_all(ui_infcontainernumber30);
    lv_obj_set_width(ui_infcontainernumber30, 200);
    lv_obj_set_height(ui_infcontainernumber30, 80);
    lv_obj_set_align(ui_infcontainernumber30, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber30 = lv_imgbtn_create(ui_infcontainernumber30);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber30, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber30, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber30, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber30, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber30, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber30, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber30, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber30, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber30, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber30, 4);

    ui_label1number30 = lv_label_create(ui_infcontainernumber30);
    lv_obj_set_width(ui_label1number30, 129);
    lv_obj_set_height(ui_label1number30, 50);
    lv_obj_set_x(ui_label1number30, 3);
    lv_obj_set_y(ui_label1number30, -12);
    lv_obj_set_align(ui_label1number30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number30, "青岛啤酒鸭17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number30, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number30 = lv_label_create(ui_infcontainernumber30);
    lv_obj_set_width(ui_label2number30, 129);
    lv_obj_set_height(ui_label2number30, 20);
    lv_obj_set_x(ui_label2number30, 3);
    lv_obj_set_y(ui_label2number30, 23);
    lv_obj_set_align(ui_label2number30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number30, "已购买");
    lv_obj_set_style_text_font(ui_label2number30, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber30 = lv_imgbtn_create(ui_infcontainernumber30);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber30, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber30, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber30, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber30, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber30, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber30, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber30, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber30, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber30, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber30, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber30, LV_ALIGN_CENTER);

    ui_number29 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number29);
    lv_obj_set_width(ui_number29, 200);
    lv_obj_set_height(ui_number29, 200);
    lv_obj_set_x(ui_number29, -716);
    lv_obj_set_y(ui_number29, -186);
    lv_obj_set_align(ui_number29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumbe29 = lv_img_create(ui_number29);
    lv_img_set_src(ui_Imagenumbe29, &ui_img_1098883221);
    lv_obj_set_width(ui_Imagenumbe29, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumbe29, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumbe29, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumbe29, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumbe29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber29 = lv_obj_create(ui_number29);
    lv_obj_remove_style_all(ui_infcontainernumber29);
    lv_obj_set_width(ui_infcontainernumber29, 200);
    lv_obj_set_height(ui_infcontainernumber29, 80);
    lv_obj_set_align(ui_infcontainernumber29, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber29 = lv_imgbtn_create(ui_infcontainernumber29);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber29, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber29, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber29, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber29, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber29, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber29, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber29, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber29, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber29, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber29, 4);

    ui_label1number29 = lv_label_create(ui_infcontainernumber29);
    lv_obj_set_width(ui_label1number29, 129);
    lv_obj_set_height(ui_label1number29, 50);
    lv_obj_set_x(ui_label1number29, 3);
    lv_obj_set_y(ui_label1number29, -12);
    lv_obj_set_align(ui_label1number29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number29, "西湖醋鱼17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number29, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number29 = lv_label_create(ui_infcontainernumber29);
    lv_obj_set_width(ui_label2number29, 129);
    lv_obj_set_height(ui_label2number29, 20);
    lv_obj_set_x(ui_label2number29, 3);
    lv_obj_set_y(ui_label2number29, 23);
    lv_obj_set_align(ui_label2number29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number29, "已购买");
    lv_obj_set_style_text_font(ui_label2number29, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber29 = lv_imgbtn_create(ui_infcontainernumber29);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber29, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber29, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber29, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber29, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber29, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber29, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber29, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber29, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber29, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber29, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber29, LV_ALIGN_CENTER);

    ui_number28 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number28);
    lv_obj_set_width(ui_number28, 200);
    lv_obj_set_height(ui_number28, 200);
    lv_obj_set_x(ui_number28, -716);
    lv_obj_set_y(ui_number28, -186);
    lv_obj_set_align(ui_number28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber28 = lv_img_create(ui_number28);
    lv_img_set_src(ui_Imagenumber28, &ui_img_4629151);
    lv_obj_set_width(ui_Imagenumber28, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber28, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber28, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber28 = lv_obj_create(ui_number28);
    lv_obj_remove_style_all(ui_infcontainernumber28);
    lv_obj_set_width(ui_infcontainernumber28, 200);
    lv_obj_set_height(ui_infcontainernumber28, 80);
    lv_obj_set_align(ui_infcontainernumber28, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber28 = lv_imgbtn_create(ui_infcontainernumber28);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber28, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber28, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber28, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber28, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber28, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber28, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber28, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber28, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber28, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber28, 4);

    ui_label1number28 = lv_label_create(ui_infcontainernumber28);
    lv_obj_set_width(ui_label1number28, 129);
    lv_obj_set_height(ui_label1number28, 50);
    lv_obj_set_x(ui_label1number28, 3);
    lv_obj_set_y(ui_label1number28, -12);
    lv_obj_set_align(ui_label1number28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number28, "手抓饼17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number28, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number28 = lv_label_create(ui_infcontainernumber28);
    lv_obj_set_width(ui_label2number28, 129);
    lv_obj_set_height(ui_label2number28, 20);
    lv_obj_set_x(ui_label2number28, 3);
    lv_obj_set_y(ui_label2number28, 23);
    lv_obj_set_align(ui_label2number28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number28, "已购买");
    lv_obj_set_style_text_font(ui_label2number28, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber28 = lv_imgbtn_create(ui_infcontainernumber28);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber28, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber28, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber28, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber28, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber28, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber28, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber28, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber28, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber28, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber28, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber28, LV_ALIGN_CENTER);

    ui_number27 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number27);
    lv_obj_set_width(ui_number27, 200);
    lv_obj_set_height(ui_number27, 200);
    lv_obj_set_x(ui_number27, -716);
    lv_obj_set_y(ui_number27, -186);
    lv_obj_set_align(ui_number27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber27 = lv_img_create(ui_number27);
    lv_img_set_src(ui_Imagenumber27, &ui_img_1081994314);
    lv_obj_set_width(ui_Imagenumber27, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber27, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber27, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber27 = lv_obj_create(ui_number27);
    lv_obj_remove_style_all(ui_infcontainernumber27);
    lv_obj_set_width(ui_infcontainernumber27, 200);
    lv_obj_set_height(ui_infcontainernumber27, 80);
    lv_obj_set_align(ui_infcontainernumber27, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber27 = lv_imgbtn_create(ui_infcontainernumber27);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber27, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber27, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber27, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber27, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber27, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber27, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber27, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber27, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber27, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber27, 4);

    ui_label1number27 = lv_label_create(ui_infcontainernumber27);
    lv_obj_set_width(ui_label1number27, 129);
    lv_obj_set_height(ui_label1number27, 50);
    lv_obj_set_x(ui_label1number27, 3);
    lv_obj_set_y(ui_label1number27, -12);
    lv_obj_set_align(ui_label1number27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number27, "烤肉拌饭17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number27, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number27 = lv_label_create(ui_infcontainernumber27);
    lv_obj_set_width(ui_label2number27, 129);
    lv_obj_set_height(ui_label2number27, 20);
    lv_obj_set_x(ui_label2number27, 3);
    lv_obj_set_y(ui_label2number27, 23);
    lv_obj_set_align(ui_label2number27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number27, "已购买");
    lv_obj_set_style_text_font(ui_label2number27, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber27 = lv_imgbtn_create(ui_infcontainernumber27);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber27, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber27, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber27, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber27, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber27, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber27, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber27, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber27, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber27, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber27, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber27, LV_ALIGN_CENTER);

    ui_number26 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number26);
    lv_obj_set_width(ui_number26, 200);
    lv_obj_set_height(ui_number26, 200);
    lv_obj_set_x(ui_number26, -716);
    lv_obj_set_y(ui_number26, -186);
    lv_obj_set_align(ui_number26, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber26 = lv_img_create(ui_number26);
    lv_img_set_src(ui_Imagenumber26, &ui_img_1980033473);
    lv_obj_set_width(ui_Imagenumber26, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber26, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber26, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber26 = lv_obj_create(ui_number26);
    lv_obj_remove_style_all(ui_infcontainernumber26);
    lv_obj_set_width(ui_infcontainernumber26, 200);
    lv_obj_set_height(ui_infcontainernumber26, 80);
    lv_obj_set_align(ui_infcontainernumber26, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber26 = lv_imgbtn_create(ui_infcontainernumber26);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber26, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber26, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber26, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber26, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber26, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber26, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber26, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber26, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber26, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber26, 4);

    ui_label1number26 = lv_label_create(ui_infcontainernumber26);
    lv_obj_set_width(ui_label1number26, 129);
    lv_obj_set_height(ui_label1number26, 50);
    lv_obj_set_x(ui_label1number26, 3);
    lv_obj_set_y(ui_label1number26, -12);
    lv_obj_set_align(ui_label1number26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number26, "烧鹅29\n会员价20");
    lv_obj_set_style_text_font(ui_label1number26, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number26 = lv_label_create(ui_infcontainernumber26);
    lv_obj_set_width(ui_label2number26, 129);
    lv_obj_set_height(ui_label2number26, 20);
    lv_obj_set_x(ui_label2number26, 3);
    lv_obj_set_y(ui_label2number26, 23);
    lv_obj_set_align(ui_label2number26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number26, "已购买");
    lv_obj_set_style_text_font(ui_label2number26, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber26 = lv_imgbtn_create(ui_infcontainernumber26);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber26, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber26, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber26, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber26, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber26, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber26, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber26, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber26, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber26, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber26, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber26, LV_ALIGN_CENTER);

    ui_number25 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number25);
    lv_obj_set_width(ui_number25, 200);
    lv_obj_set_height(ui_number25, 200);
    lv_obj_set_x(ui_number25, -716);
    lv_obj_set_y(ui_number25, -186);
    lv_obj_set_align(ui_number25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber25 = lv_img_create(ui_number25);
    lv_img_set_src(ui_Imagenumber25, &ui_img_990302588);
    lv_obj_set_width(ui_Imagenumber25, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber25, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber25, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber25 = lv_obj_create(ui_number25);
    lv_obj_remove_style_all(ui_infcontainernumber25);
    lv_obj_set_width(ui_infcontainernumber25, 200);
    lv_obj_set_height(ui_infcontainernumber25, 80);
    lv_obj_set_align(ui_infcontainernumber25, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber25 = lv_imgbtn_create(ui_infcontainernumber25);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber25, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber25, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber25, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber25, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber25, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber25, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber25, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber25, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber25, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber25, 4);

    ui_label1number25 = lv_label_create(ui_infcontainernumber25);
    lv_obj_set_width(ui_label1number25, 129);
    lv_obj_set_height(ui_label1number25, 50);
    lv_obj_set_x(ui_label1number25, 3);
    lv_obj_set_y(ui_label1number25, -12);
    lv_obj_set_align(ui_label1number25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number25, "泡脚凤爪47\n会员价39");
    lv_obj_set_style_text_font(ui_label1number25, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number25 = lv_label_create(ui_infcontainernumber25);
    lv_obj_set_width(ui_label2number25, 129);
    lv_obj_set_height(ui_label2number25, 20);
    lv_obj_set_x(ui_label2number25, 3);
    lv_obj_set_y(ui_label2number25, 23);
    lv_obj_set_align(ui_label2number25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number25, "已购买");
    lv_obj_set_style_text_font(ui_label2number25, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber25 = lv_imgbtn_create(ui_infcontainernumber25);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber25, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber25, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber25, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber25, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber25, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber25, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber25, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber25, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber25, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber25, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber25, LV_ALIGN_CENTER);

    ui_number24 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number24);
    lv_obj_set_width(ui_number24, 200);
    lv_obj_set_height(ui_number24, 200);
    lv_obj_set_x(ui_number24, -716);
    lv_obj_set_y(ui_number24, -186);
    lv_obj_set_align(ui_number24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber24 = lv_img_create(ui_number24);
    lv_img_set_src(ui_Imagenumber24, &ui_img_1056385595);
    lv_obj_set_width(ui_Imagenumber24, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber24, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber24, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber24 = lv_obj_create(ui_number24);
    lv_obj_remove_style_all(ui_infcontainernumber24);
    lv_obj_set_width(ui_infcontainernumber24, 200);
    lv_obj_set_height(ui_infcontainernumber24, 80);
    lv_obj_set_align(ui_infcontainernumber24, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber24 = lv_imgbtn_create(ui_infcontainernumber24);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber24, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber24, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber24, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber24, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber24, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber24, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber24, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber24, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber24, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber24, 4);

    ui_label1number24 = lv_label_create(ui_infcontainernumber24);
    lv_obj_set_width(ui_label1number24, 129);
    lv_obj_set_height(ui_label1number24, 50);
    lv_obj_set_x(ui_label1number24, 3);
    lv_obj_set_y(ui_label1number24, -12);
    lv_obj_set_align(ui_label1number24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number24, "辣子鸡17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number24, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number24 = lv_label_create(ui_infcontainernumber24);
    lv_obj_set_width(ui_label2number24, 129);
    lv_obj_set_height(ui_label2number24, 20);
    lv_obj_set_x(ui_label2number24, 3);
    lv_obj_set_y(ui_label2number24, 23);
    lv_obj_set_align(ui_label2number24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number24, "已购买");
    lv_obj_set_style_text_font(ui_label2number24, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber24 = lv_imgbtn_create(ui_infcontainernumber24);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber24, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber24, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber24, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber24, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber24, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber24, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber24, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber24, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber24, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber24, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber24, LV_ALIGN_CENTER);

    ui_number23 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number23);
    lv_obj_set_width(ui_number23, 200);
    lv_obj_set_height(ui_number23, 200);
    lv_obj_set_x(ui_number23, -716);
    lv_obj_set_y(ui_number23, -186);
    lv_obj_set_align(ui_number23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber23 = lv_img_create(ui_number23);
    lv_img_set_src(ui_Imagenumber23, &ui_img_2103126394);
    lv_obj_set_width(ui_Imagenumber23, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber23, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber23, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber23 = lv_obj_create(ui_number23);
    lv_obj_remove_style_all(ui_infcontainernumber23);
    lv_obj_set_width(ui_infcontainernumber23, 200);
    lv_obj_set_height(ui_infcontainernumber23, 80);
    lv_obj_set_align(ui_infcontainernumber23, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber23 = lv_imgbtn_create(ui_infcontainernumber23);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber23, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber23, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber23, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber23, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber23, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber23, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber23, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber23, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber23, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber23, 4);

    ui_label1number23 = lv_label_create(ui_infcontainernumber23);
    lv_obj_set_width(ui_label1number23, 129);
    lv_obj_set_height(ui_label1number23, 50);
    lv_obj_set_x(ui_label1number23, 3);
    lv_obj_set_y(ui_label1number23, -12);
    lv_obj_set_align(ui_label1number23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number23, "毛血旺46\n会员价35");
    lv_obj_set_style_text_font(ui_label1number23, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number23 = lv_label_create(ui_infcontainernumber23);
    lv_obj_set_width(ui_label2number23, 129);
    lv_obj_set_height(ui_label2number23, 20);
    lv_obj_set_x(ui_label2number23, 3);
    lv_obj_set_y(ui_label2number23, 23);
    lv_obj_set_align(ui_label2number23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number23, "已购买");
    lv_obj_set_style_text_font(ui_label2number23, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber23 = lv_imgbtn_create(ui_infcontainernumber23);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber23, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber23, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber23, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber23, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber23, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber23, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber23, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber23, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber23, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber23, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber23, LV_ALIGN_CENTER);

    ui_number22 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number22);
    lv_obj_set_width(ui_number22, 200);
    lv_obj_set_height(ui_number22, 200);
    lv_obj_set_x(ui_number22, -716);
    lv_obj_set_y(ui_number22, -186);
    lv_obj_set_align(ui_number22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber22 = lv_img_create(ui_number22);
    lv_img_set_src(ui_Imagenumber22, &ui_img_1483454965);
    lv_obj_set_width(ui_Imagenumber22, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber22, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber22, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber22 = lv_obj_create(ui_number22);
    lv_obj_remove_style_all(ui_infcontainernumber22);
    lv_obj_set_width(ui_infcontainernumber22, 200);
    lv_obj_set_height(ui_infcontainernumber22, 80);
    lv_obj_set_align(ui_infcontainernumber22, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber22 = lv_imgbtn_create(ui_infcontainernumber22);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber22, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber22, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber22, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber22, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber22, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber22, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber22, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber22, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber22, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber22, 4);

    ui_label1number22 = lv_label_create(ui_infcontainernumber22);
    lv_obj_set_width(ui_label1number22, 129);
    lv_obj_set_height(ui_label1number22, 50);
    lv_obj_set_x(ui_label1number22, 3);
    lv_obj_set_y(ui_label1number22, -12);
    lv_obj_set_align(ui_label1number22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number22, "干煸豆角32\n会员价25");
    lv_obj_set_style_text_font(ui_label1number22, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number22 = lv_label_create(ui_infcontainernumber22);
    lv_obj_set_width(ui_label2number22, 129);
    lv_obj_set_height(ui_label2number22, 20);
    lv_obj_set_x(ui_label2number22, 3);
    lv_obj_set_y(ui_label2number22, 23);
    lv_obj_set_align(ui_label2number22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number22, "已购买");
    lv_obj_set_style_text_font(ui_label2number22, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber22 = lv_imgbtn_create(ui_infcontainernumber22);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber22, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber22, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber22, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber22, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber22, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber22, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber22, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber22, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber22, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber22, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber22, LV_ALIGN_CENTER);

    ui_number21 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_number21);
    lv_obj_set_width(ui_number21, 200);
    lv_obj_set_height(ui_number21, 200);
    lv_obj_set_x(ui_number21, -716);
    lv_obj_set_y(ui_number21, -186);
    lv_obj_set_align(ui_number21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber21 = lv_img_create(ui_number21);
    lv_img_set_src(ui_Imagenumber21, &ui_img_1051774729);
    lv_obj_set_width(ui_Imagenumber21, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber21, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber21, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber21 = lv_obj_create(ui_number21);
    lv_obj_remove_style_all(ui_infcontainernumber21);
    lv_obj_set_width(ui_infcontainernumber21, 200);
    lv_obj_set_height(ui_infcontainernumber21, 80);
    lv_obj_set_align(ui_infcontainernumber21, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber21 = lv_imgbtn_create(ui_infcontainernumber21);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber21, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber21, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber21, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber21, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber21, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber21, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber21, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber21, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber21, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber21, 4);

    ui_label1number21 = lv_label_create(ui_infcontainernumber21);
    lv_obj_set_width(ui_label1number21, 129);
    lv_obj_set_height(ui_label1number21, 50);
    lv_obj_set_x(ui_label1number21, 3);
    lv_obj_set_y(ui_label1number21, -12);
    lv_obj_set_align(ui_label1number21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number21, "叉烧17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number21, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number21 = lv_label_create(ui_infcontainernumber21);
    lv_obj_set_width(ui_label2number21, 129);
    lv_obj_set_height(ui_label2number21, 20);
    lv_obj_set_x(ui_label2number21, 3);
    lv_obj_set_y(ui_label2number21, 23);
    lv_obj_set_align(ui_label2number21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number21, "已购买");
    lv_obj_set_style_text_font(ui_label2number21, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber21 = lv_imgbtn_create(ui_infcontainernumber21);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber21, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber21, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber21, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber21, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber21, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber21, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber21, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber21, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber21, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber21, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber21, LV_ALIGN_CENTER);

    ui_lastpageButon3 = lv_imgbtn_create(ui_order3);
    lv_imgbtn_set_src(ui_lastpageButon3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_lastpageButon3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_lastpageButon3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButon3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButon3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButon3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_lastpageButon3, 64);
    lv_obj_set_width(ui_lastpageButon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_lastpageButon3, -82);
    lv_obj_set_y(ui_lastpageButon3, 245);
    lv_obj_set_align(ui_lastpageButon3, LV_ALIGN_CENTER);

    ui_nextpageButon3 = lv_imgbtn_create(ui_order3);
    lv_imgbtn_set_src(ui_nextpageButon3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_nextpageButon3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_nextpageButon3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButon3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButon3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButon3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_nextpageButon3, 64);
    lv_obj_set_width(ui_nextpageButon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_nextpageButon3, 140);
    lv_obj_set_y(ui_nextpageButon3, 245);
    lv_obj_set_align(ui_nextpageButon3, LV_ALIGN_CENTER);

    ui_backButton4 = lv_imgbtn_create(ui_order3);
    lv_imgbtn_set_src(ui_backButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_backButton4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_backButton4, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton4, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton4, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton4, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_backButton4, 50);
    lv_obj_set_height(ui_backButton4, 30);
    lv_obj_set_x(ui_backButton4, -482);
    lv_obj_set_y(ui_backButton4, 282);
    lv_obj_set_align(ui_backButton4, LV_ALIGN_CENTER);

     ui_Buttonconfirm3 = lv_btn_create(ui_order3);
    lv_obj_set_width(ui_Buttonconfirm3, 100);
    lv_obj_set_height(ui_Buttonconfirm3, 50);
    lv_obj_set_x(ui_Buttonconfirm3, 18);
    lv_obj_set_y(ui_Buttonconfirm3, 242);
    lv_obj_set_align(ui_Buttonconfirm3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonconfirm3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonconfirm3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelconfirm3 = lv_label_create(ui_Buttonconfirm3);
    lv_obj_set_width(ui_Labelconfirm3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelconfirm3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelconfirm3, -1);
    lv_obj_set_y(ui_Labelconfirm3, 4);
    lv_obj_set_align(ui_Labelconfirm3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelconfirm3, "结账");
    lv_obj_set_style_text_font(ui_Labelconfirm3, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_lastpageButon3, ui_event_lastpageButon3, LV_EVENT_ALL, NULL);

}
