// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: order2

#include "../ui.h"

void ui_order2_screen_init(void)
{
    ui_order2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_order2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_order2, &ui_img_1485140228, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_order2);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 1024);
    lv_obj_set_height(ui_Container7, 400);
    lv_obj_set_x(ui_Container7, 0);
    lv_obj_set_y(ui_Container7, -100);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number20 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number20);
    lv_obj_set_width(ui_number20, 200);
    lv_obj_set_height(ui_number20, 200);
    lv_obj_set_x(ui_number20, -716);
    lv_obj_set_y(ui_number20, -186);
    lv_obj_set_align(ui_number20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber20 = lv_img_create(ui_number20);
    lv_img_set_src(ui_Imagenumber20, &ui_img_814352610);
    lv_obj_set_width(ui_Imagenumber20, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber20, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber20, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber20 = lv_obj_create(ui_number20);
    lv_obj_remove_style_all(ui_infcontainernumber20);
    lv_obj_set_width(ui_infcontainernumber20, 200);
    lv_obj_set_height(ui_infcontainernumber20, 80);
    lv_obj_set_align(ui_infcontainernumber20, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber20 = lv_imgbtn_create(ui_infcontainernumber20);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber20, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber20, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber20, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber20, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber20, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber20, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber20, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber20, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber20, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber20, 4);

    ui_label1number20 = lv_label_create(ui_infcontainernumber20);
    lv_obj_set_width(ui_label1number20, 129);
    lv_obj_set_height(ui_label1number20, 50);
    lv_obj_set_x(ui_label1number20, 3);
    lv_obj_set_y(ui_label1number20, -12);
    lv_obj_set_align(ui_label1number20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number20, "猪肉炖粉条17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number20, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number20 = lv_label_create(ui_infcontainernumber20);
    lv_obj_set_width(ui_label2number20, 129);
    lv_obj_set_height(ui_label2number20, 20);
    lv_obj_set_x(ui_label2number20, 3);
    lv_obj_set_y(ui_label2number20, 23);
    lv_obj_set_align(ui_label2number20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number20, "已购买");
    lv_obj_set_style_text_font(ui_label2number20, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber20 = lv_imgbtn_create(ui_infcontainernumber20);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber20, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber20, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber20, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber20, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber20, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber20, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber20, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber20, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber20, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber20, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber20, LV_ALIGN_CENTER);

    ui_number19 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number19);
    lv_obj_set_width(ui_number19, 200);
    lv_obj_set_height(ui_number19, 200);
    lv_obj_set_x(ui_number19, -716);
    lv_obj_set_y(ui_number19, -186);
    lv_obj_set_align(ui_number19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber19 = lv_img_create(ui_number19);
    lv_img_set_src(ui_Imagenumber19, &ui_img_1429700948);
    lv_obj_set_width(ui_Imagenumber19, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber19, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber19, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber19 = lv_obj_create(ui_number19);
    lv_obj_remove_style_all(ui_infcontainernumber19);
    lv_obj_set_width(ui_infcontainernumber19, 200);
    lv_obj_set_height(ui_infcontainernumber19, 80);
    lv_obj_set_align(ui_infcontainernumber19, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber19 = lv_imgbtn_create(ui_infcontainernumber19);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber19, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber19, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber19, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber19, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber19, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber19, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber19, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber19, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber19, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber19, 4);

    ui_label1number19 = lv_label_create(ui_infcontainernumber19);
    lv_obj_set_width(ui_label1number19, 129);
    lv_obj_set_height(ui_label1number19, 50);
    lv_obj_set_x(ui_label1number19, 3);
    lv_obj_set_y(ui_label1number19, -12);
    lv_obj_set_align(ui_label1number19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number19, "番茄炒蛋32\n会员价25");
    lv_obj_set_style_text_font(ui_label1number19, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number19 = lv_label_create(ui_infcontainernumber19);
    lv_obj_set_width(ui_label2number19, 129);
    lv_obj_set_height(ui_label2number19, 20);
    lv_obj_set_x(ui_label2number19, 3);
    lv_obj_set_y(ui_label2number19, 23);
    lv_obj_set_align(ui_label2number19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number19, "已购买");
    lv_obj_set_style_text_font(ui_label2number19, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber19 = lv_imgbtn_create(ui_infcontainernumber19);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber19, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber19, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber19, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber19, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber19, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber19, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber19, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber19, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber19, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber19, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber19, LV_ALIGN_CENTER);

    ui_number18 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number18);
    lv_obj_set_width(ui_number18, 200);
    lv_obj_set_height(ui_number18, 200);
    lv_obj_set_x(ui_number18, -716);
    lv_obj_set_y(ui_number18, -186);
    lv_obj_set_align(ui_number18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber18 = lv_img_create(ui_number18);
    lv_img_set_src(ui_Imagenumber18, &ui_img_403749227);
    lv_obj_set_width(ui_Imagenumber18, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber18, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber18, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber18 = lv_obj_create(ui_number18);
    lv_obj_remove_style_all(ui_infcontainernumber18);
    lv_obj_set_width(ui_infcontainernumber18, 200);
    lv_obj_set_height(ui_infcontainernumber18, 80);
    lv_obj_set_align(ui_infcontainernumber18, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber18 = lv_imgbtn_create(ui_infcontainernumber18);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber18, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber18, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber18, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber18, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber18, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber18, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber18, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber18, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber18, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber18, 4);

    ui_labelnumber18 = lv_label_create(ui_infcontainernumber18);
    lv_obj_set_width(ui_labelnumber18, 129);
    lv_obj_set_height(ui_labelnumber18, 50);
    lv_obj_set_x(ui_labelnumber18, 3);
    lv_obj_set_y(ui_labelnumber18, -12);
    lv_obj_set_align(ui_labelnumber18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelnumber18, "紫苏田螺46\n会员价35");
    lv_obj_set_style_text_font(ui_labelnumber18, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1number18 = lv_label_create(ui_infcontainernumber18);
    lv_obj_set_width(ui_label1number18, 129);
    lv_obj_set_height(ui_label1number18, 20);
    lv_obj_set_x(ui_label1number18, 3);
    lv_obj_set_y(ui_label1number18, 23);
    lv_obj_set_align(ui_label1number18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number18, "已购买");
    lv_obj_set_style_text_font(ui_label1number18, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber18 = lv_imgbtn_create(ui_infcontainernumber18);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber18, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber18, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber18, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber18, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber18, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber18, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber18, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber18, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber18, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber18, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber18, LV_ALIGN_CENTER);

    ui_number17 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number17);
    lv_obj_set_width(ui_number17, 200);
    lv_obj_set_height(ui_number17, 200);
    lv_obj_set_x(ui_number17, -716);
    lv_obj_set_y(ui_number17, -186);
    lv_obj_set_align(ui_number17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber17 = lv_img_create(ui_number17);
    lv_img_set_src(ui_Imagenumber17, &ui_img_784203148);
    lv_obj_set_width(ui_Imagenumber17, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber17, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber17, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber17 = lv_obj_create(ui_number17);
    lv_obj_remove_style_all(ui_infcontainernumber17);
    lv_obj_set_width(ui_infcontainernumber17, 200);
    lv_obj_set_height(ui_infcontainernumber17, 80);
    lv_obj_set_align(ui_infcontainernumber17, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber17 = lv_imgbtn_create(ui_infcontainernumber17);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber17, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber17, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber17, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber17, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber17, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber17, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber17, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber17, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber17, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber17, 4);

    ui_label5number17 = lv_label_create(ui_infcontainernumber17);
    lv_obj_set_width(ui_label5number17, 129);
    lv_obj_set_height(ui_label5number17, 50);
    lv_obj_set_x(ui_label5number17, 3);
    lv_obj_set_y(ui_label5number17, -12);
    lv_obj_set_align(ui_label5number17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label5number17, "红烧带鱼17\n会员价15");
    lv_obj_set_style_text_font(ui_label5number17, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1number17 = lv_label_create(ui_infcontainernumber17);
    lv_obj_set_width(ui_label1number17, 129);
    lv_obj_set_height(ui_label1number17, 20);
    lv_obj_set_x(ui_label1number17, 3);
    lv_obj_set_y(ui_label1number17, 23);
    lv_obj_set_align(ui_label1number17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number17, "已购买");
    lv_obj_set_style_text_font(ui_label1number17, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonright3number17 = lv_imgbtn_create(ui_infcontainernumber17);
    lv_imgbtn_set_src(ui_ImgButtonright3number17, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number17, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number17, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number17, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number17, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number17, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonright3number17, 30);
    lv_obj_set_height(ui_ImgButtonright3number17, 40);
    lv_obj_set_x(ui_ImgButtonright3number17, 82);
    lv_obj_set_y(ui_ImgButtonright3number17, -16);
    lv_obj_set_align(ui_ImgButtonright3number17, LV_ALIGN_CENTER);

    ui_number16 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number16);
    lv_obj_set_width(ui_number16, 200);
    lv_obj_set_height(ui_number16, 200);
    lv_obj_set_x(ui_number16, -716);
    lv_obj_set_y(ui_number16, -186);
    lv_obj_set_align(ui_number16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber16 = lv_img_create(ui_number16);
    lv_img_set_src(ui_Imagenumber16, &ui_img_462669028);
    lv_obj_set_width(ui_Imagenumber16, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber16, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber16, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber16 = lv_obj_create(ui_number16);
    lv_obj_remove_style_all(ui_infcontainernumber16);
    lv_obj_set_width(ui_infcontainernumber16, 200);
    lv_obj_set_height(ui_infcontainernumber16, 80);
    lv_obj_set_align(ui_infcontainernumber16, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber16 = lv_imgbtn_create(ui_infcontainernumber16);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber16, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber16, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber16, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber16, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber16, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber16, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber16, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber16, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber16, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber16, 4);

    ui_label1number16 = lv_label_create(ui_infcontainernumber16);
    lv_obj_set_width(ui_label1number16, 129);
    lv_obj_set_height(ui_label1number16, 50);
    lv_obj_set_x(ui_label1number16, 3);
    lv_obj_set_y(ui_label1number16, -12);
    lv_obj_set_align(ui_label1number16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number16, "红烧排骨47\n会员价39");
    lv_obj_set_style_text_font(ui_label1number16, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number16 = lv_label_create(ui_infcontainernumber16);
    lv_obj_set_width(ui_label2number16, 129);
    lv_obj_set_height(ui_label2number16, 20);
    lv_obj_set_x(ui_label2number16, 3);
    lv_obj_set_y(ui_label2number16, 23);
    lv_obj_set_align(ui_label2number16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number16, "已购买");
    lv_obj_set_style_text_font(ui_label2number16, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber16 = lv_imgbtn_create(ui_infcontainernumber16);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber16, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber16, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber16, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber16, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber16, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber16, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber16, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber16, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber16, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber16, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber16, LV_ALIGN_CENTER);

    ui_number15 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number15);
    lv_obj_set_width(ui_number15, 200);
    lv_obj_set_height(ui_number15, 200);
    lv_obj_set_x(ui_number15, -716);
    lv_obj_set_y(ui_number15, -186);
    lv_obj_set_align(ui_number15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber15 = lv_img_create(ui_number15);
    lv_img_set_src(ui_Imagenumber15, &ui_img_1181513690);
    lv_obj_set_width(ui_Imagenumber15, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber15, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber15, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber15 = lv_obj_create(ui_number15);
    lv_obj_remove_style_all(ui_infcontainernumber15);
    lv_obj_set_width(ui_infcontainernumber15, 200);
    lv_obj_set_height(ui_infcontainernumber15, 80);
    lv_obj_set_align(ui_infcontainernumber15, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber15 = lv_imgbtn_create(ui_infcontainernumber15);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber15, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber15, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber15, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber15, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber15, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber15, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber15, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber15, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber15, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber15, 4);

    ui_label1number15 = lv_label_create(ui_infcontainernumber15);
    lv_obj_set_width(ui_label1number15, 129);
    lv_obj_set_height(ui_label1number15, 50);
    lv_obj_set_x(ui_label1number15, 3);
    lv_obj_set_y(ui_label1number15, -12);
    lv_obj_set_align(ui_label1number15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number15, "红烧狮子头29\n会员价20");
    lv_obj_set_style_text_font(ui_label1number15, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number15 = lv_label_create(ui_infcontainernumber15);
    lv_obj_set_width(ui_label2number15, 129);
    lv_obj_set_height(ui_label2number15, 20);
    lv_obj_set_x(ui_label2number15, 3);
    lv_obj_set_y(ui_label2number15, 23);
    lv_obj_set_align(ui_label2number15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number15, "已购买");
    lv_obj_set_style_text_font(ui_label2number15, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber15 = lv_imgbtn_create(ui_infcontainernumber15);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber15, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber15, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber15, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber15, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber15, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber15, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber15, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber15, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber15, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber15, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber15, LV_ALIGN_CENTER);

    ui_number14 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number14);
    lv_obj_set_width(ui_number14, 200);
    lv_obj_set_height(ui_number14, 200);
    lv_obj_set_x(ui_number14, -716);
    lv_obj_set_y(ui_number14, -186);
    lv_obj_set_align(ui_number14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber14 = lv_img_create(ui_number14);
    lv_img_set_src(ui_Imagenumber14, &ui_img_139154128);
    lv_obj_set_width(ui_Imagenumber14, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber14, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber14, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber14 = lv_obj_create(ui_number14);
    lv_obj_remove_style_all(ui_infcontainernumber14);
    lv_obj_set_width(ui_infcontainernumber14, 200);
    lv_obj_set_height(ui_infcontainernumber14, 80);
    lv_obj_set_align(ui_infcontainernumber14, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber14 = lv_imgbtn_create(ui_infcontainernumber14);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber14, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber14, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber14, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber14, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber14, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber14, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber14, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber14, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber14, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber14, 4);

    ui_label1number14 = lv_label_create(ui_infcontainernumber14);
    lv_obj_set_width(ui_label1number14, 129);
    lv_obj_set_height(ui_label1number14, 50);
    lv_obj_set_x(ui_label1number14, 3);
    lv_obj_set_y(ui_label1number14, -12);
    lv_obj_set_align(ui_label1number14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number14, "锅包肉17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number14, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number14 = lv_label_create(ui_infcontainernumber14);
    lv_obj_set_width(ui_label2number14, 129);
    lv_obj_set_height(ui_label2number14, 20);
    lv_obj_set_x(ui_label2number14, 3);
    lv_obj_set_y(ui_label2number14, 23);
    lv_obj_set_align(ui_label2number14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number14, "已购买");
    lv_obj_set_style_text_font(ui_label2number14, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber14 = lv_imgbtn_create(ui_infcontainernumber14);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber14, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber14, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber14, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber14, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber14, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber14, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber14, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber14, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber14, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber14, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber14, LV_ALIGN_CENTER);

    ui_number13 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number13);
    lv_obj_set_width(ui_number13, 200);
    lv_obj_set_height(ui_number13, 200);
    lv_obj_set_x(ui_number13, -716);
    lv_obj_set_y(ui_number13, -186);
    lv_obj_set_align(ui_number13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber13 = lv_img_create(ui_number13);
    lv_img_set_src(ui_Imagenumber13, &ui_img_2035788098);
    lv_obj_set_width(ui_Imagenumber13, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber13, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber13, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber13 = lv_obj_create(ui_number13);
    lv_obj_remove_style_all(ui_infcontainernumber13);
    lv_obj_set_width(ui_infcontainernumber13, 200);
    lv_obj_set_height(ui_infcontainernumber13, 80);
    lv_obj_set_align(ui_infcontainernumber13, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber13 = lv_imgbtn_create(ui_infcontainernumber13);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber13, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber13, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber13, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber13, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber13, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber13, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber13, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber13, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber13, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber13, 4);

    ui_label1number13 = lv_label_create(ui_infcontainernumber13);
    lv_obj_set_width(ui_label1number13, 129);
    lv_obj_set_height(ui_label1number13, 50);
    lv_obj_set_x(ui_label1number13, 3);
    lv_obj_set_y(ui_label1number13, -12);
    lv_obj_set_align(ui_label1number13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number13, "麻婆豆腐17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number13, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number13 = lv_label_create(ui_infcontainernumber13);
    lv_obj_set_width(ui_label2number13, 129);
    lv_obj_set_height(ui_label2number13, 20);
    lv_obj_set_x(ui_label2number13, 3);
    lv_obj_set_y(ui_label2number13, 23);
    lv_obj_set_align(ui_label2number13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number13, "已购买");
    lv_obj_set_style_text_font(ui_label2number13, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber13 = lv_imgbtn_create(ui_infcontainernumber13);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber13, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber13, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber13, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber13, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber13, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber13, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber13, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber13, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber13, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber13, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber13, LV_ALIGN_CENTER);

    ui_number12 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number12);
    lv_obj_set_width(ui_number12, 200);
    lv_obj_set_height(ui_number12, 200);
    lv_obj_set_x(ui_number12, -716);
    lv_obj_set_y(ui_number12, -186);
    lv_obj_set_align(ui_number12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumbe12 = lv_img_create(ui_number12);
    lv_img_set_src(ui_Imagenumbe12, &ui_img_412946995);
    lv_obj_set_width(ui_Imagenumbe12, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumbe12, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumbe12, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumbe12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumbe12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber12 = lv_obj_create(ui_number12);
    lv_obj_remove_style_all(ui_infcontainernumber12);
    lv_obj_set_width(ui_infcontainernumber12, 200);
    lv_obj_set_height(ui_infcontainernumber12, 80);
    lv_obj_set_align(ui_infcontainernumber12, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber12 = lv_imgbtn_create(ui_infcontainernumber12);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber12, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber12, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber12, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber12, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber12, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber12, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber12, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber12, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber12, 4);

    ui_label1number12 = lv_label_create(ui_infcontainernumber12);
    lv_obj_set_width(ui_label1number12, 129);
    lv_obj_set_height(ui_label1number12, 50);
    lv_obj_set_x(ui_label1number12, 3);
    lv_obj_set_y(ui_label1number12, -12);
    lv_obj_set_align(ui_label1number12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number12, "小炒肉17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number12, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number12 = lv_label_create(ui_infcontainernumber12);
    lv_obj_set_width(ui_label2number12, 129);
    lv_obj_set_height(ui_label2number12, 20);
    lv_obj_set_x(ui_label2number12, 3);
    lv_obj_set_y(ui_label2number12, 23);
    lv_obj_set_align(ui_label2number12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number12, "已购买");
    lv_obj_set_style_text_font(ui_label2number12, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber12 = lv_imgbtn_create(ui_infcontainernumber12);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber12, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber12, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber12, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber12, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber12, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber12, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber12, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber12, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber12, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber12, LV_ALIGN_CENTER);

    ui_number11 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_number11);
    lv_obj_set_width(ui_number11, 200);
    lv_obj_set_height(ui_number11, 200);
    lv_obj_set_x(ui_number11, -716);
    lv_obj_set_y(ui_number11, -186);
    lv_obj_set_align(ui_number11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber11 = lv_img_create(ui_number11);
    lv_img_set_src(ui_Imagenumber11, &ui_img_1119412587);
    lv_obj_set_width(ui_Imagenumber11, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber11, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber11, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber11 = lv_obj_create(ui_number11);
    lv_obj_remove_style_all(ui_infcontainernumber11);
    lv_obj_set_width(ui_infcontainernumber11, 200);
    lv_obj_set_height(ui_infcontainernumber11, 80);
    lv_obj_set_align(ui_infcontainernumber11, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber11 = lv_imgbtn_create(ui_infcontainernumber11);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber11, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber11, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber11, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber11, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber11, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber11, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber11, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber11, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber11, 4);

    ui_label1number11 = lv_label_create(ui_infcontainernumber11);
    lv_obj_set_width(ui_label1number11, 129);
    lv_obj_set_height(ui_label1number11, 50);
    lv_obj_set_x(ui_label1number11, 3);
    lv_obj_set_y(ui_label1number11, -12);
    lv_obj_set_align(ui_label1number11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number11, "番茄牛肉17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number11, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number11 = lv_label_create(ui_infcontainernumber11);
    lv_obj_set_width(ui_label2number11, 129);
    lv_obj_set_height(ui_label2number11, 20);
    lv_obj_set_x(ui_label2number11, 3);
    lv_obj_set_y(ui_label2number11, 23);
    lv_obj_set_align(ui_label2number11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number11, "已购买");
    lv_obj_set_style_text_font(ui_label2number11, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber11 = lv_imgbtn_create(ui_infcontainernumber11);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber11, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber11, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber11, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber11, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber11, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber11, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber11, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber11, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber11, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber11, LV_ALIGN_CENTER);

    ui_lastpageButon2 = lv_imgbtn_create(ui_order2);
    lv_imgbtn_set_src(ui_lastpageButon2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_lastpageButon2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_lastpageButon2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButon2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButon2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButon2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_lastpageButon2, 64);
    lv_obj_set_width(ui_lastpageButon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_lastpageButon2, -82);
    lv_obj_set_y(ui_lastpageButon2, 245);
    lv_obj_set_align(ui_lastpageButon2, LV_ALIGN_CENTER);

    ui_nextpageButon2 = lv_imgbtn_create(ui_order2);
    lv_imgbtn_set_src(ui_nextpageButon2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_nextpageButon2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_nextpageButon2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButon2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButon2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButon2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_nextpageButon2, 64);
    lv_obj_set_width(ui_nextpageButon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_nextpageButon2, 140);
    lv_obj_set_y(ui_nextpageButon2, 245);
    lv_obj_set_align(ui_nextpageButon2, LV_ALIGN_CENTER);

    ui_backButton3 = lv_imgbtn_create(ui_order2);
    lv_imgbtn_set_src(ui_backButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_backButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_backButton3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_backButton3, 50);
    lv_obj_set_height(ui_backButton3, 30);
    lv_obj_set_x(ui_backButton3, -482);
    lv_obj_set_y(ui_backButton3, 282);
    lv_obj_set_align(ui_backButton3, LV_ALIGN_CENTER);

    ui_Buttonconfirm2 = lv_btn_create(ui_order2);
    lv_obj_set_width(ui_Buttonconfirm2, 100);
    lv_obj_set_height(ui_Buttonconfirm2, 50);
    lv_obj_set_x(ui_Buttonconfirm2, 18);
    lv_obj_set_y(ui_Buttonconfirm2, 242);
    lv_obj_set_align(ui_Buttonconfirm2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonconfirm2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonconfirm2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelconfirm2 = lv_label_create(ui_Buttonconfirm2);
    lv_obj_set_width(ui_Labelconfirm2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelconfirm2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelconfirm2, -1);
    lv_obj_set_y(ui_Labelconfirm2, 4);
    lv_obj_set_align(ui_Labelconfirm2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelconfirm2, "结账");
    lv_obj_set_style_text_font(ui_Labelconfirm2, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_backButton3, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lastpageButon2, ui_event_lastpageButon2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nextpageButon2, ui_event_nextpageButon2, LV_EVENT_ALL, NULL);

}
