// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void iop_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_helloscreen
void ui_helloscreen_screen_init(void);
lv_obj_t * ui_helloscreen;
lv_obj_t * ui_Container1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_bar1;
void ui_event_barLabel(lv_event_t * e);
lv_obj_t * ui_barLabel;
void ui_event_Dropdown3(lv_event_t * e);
lv_obj_t * ui_Dropdown3;


// SCREEN: ui_viplogin
void ui_viplogin_screen_init(void);
lv_obj_t * ui_viplogin;


// SCREEN: ui_orderscreen1
void ui_orderscreen1_screen_init(void);
lv_obj_t * ui_orderscreen1;
lv_obj_t * ui_Container2;
lv_obj_t * ui_number8container;
lv_obj_t * ui_number8Image;
lv_obj_t * ui_number8infcontainer;
lv_obj_t * ui_number8ImgButtonleft;
lv_obj_t * ui_number8label1;
lv_obj_t * ui_number8label2;
lv_obj_t * ui_number8ImgButtonright;
lv_obj_t * ui_number7container;
lv_obj_t * ui_number7Image;
lv_obj_t * ui_number7infcontainer;
lv_obj_t * ui_number7ImgButtonleft;
lv_obj_t * ui_number7label1;
lv_obj_t * ui_number7label2;
lv_obj_t * ui_number7ImgButtonright;
lv_obj_t * ui_number6container;
lv_obj_t * ui_number6Image;
lv_obj_t * ui_number6infcontainer;
lv_obj_t * ui_number6ImgButtonleft;
lv_obj_t * ui_number6label1;
lv_obj_t * ui_number6label2;
lv_obj_t * ui_number6ImgButtonright;
lv_obj_t * ui_number5container;
lv_obj_t * ui_number5Image;
lv_obj_t * ui_number5infcontainer;
lv_obj_t * ui_number5ImgButtonleft;
lv_obj_t * ui_number5label1;
lv_obj_t * ui_number5label2;
lv_obj_t * ui_number5ImgButtonright;
lv_obj_t * ui_number4container;
lv_obj_t * ui_number4Image;
lv_obj_t * ui_number4infcontainer;
lv_obj_t * ui_number4ImgButtonleft;
lv_obj_t * ui_number4label1;
lv_obj_t * ui_number4label2;
lv_obj_t * ui_number4ImgButtonright;
lv_obj_t * ui_number3container;
lv_obj_t * ui_number3Image;
lv_obj_t * ui_number3infcontainer;
lv_obj_t * ui_number3ImgButtonleft;
lv_obj_t * ui_number3label1;
lv_obj_t * ui_number3label2;
lv_obj_t * ui_number3ImgButtonright;
lv_obj_t * ui_number2container;
lv_obj_t * ui_number2Image;
lv_obj_t * ui_number2infcontainer;
lv_obj_t * ui_number2ImgButtonleft;
lv_obj_t * ui_number2label1;
lv_obj_t * ui_number2label2;
lv_obj_t * ui_number2ImgButtonright;
lv_obj_t * ui_number1container;
lv_obj_t * ui_number1Image;
lv_obj_t * ui_number1infcontainer;
lv_obj_t * ui_number1ImgButtonleft;
lv_obj_t * ui_number1label1;
lv_obj_t * ui_number1label2;
lv_obj_t * ui_number1ImgButtonright;
lv_obj_t * ui_Container4;
lv_obj_t * ui_lastpageButton1;
void ui_event_nextpageButton2(lv_event_t * e);
lv_obj_t * ui_nextpageButton2;
void ui_event_backButton1(lv_event_t * e);
lv_obj_t * ui_backButton1;
lv_obj_t * ui_confirmButton1;
lv_obj_t * ui_confirmLabel1;


// SCREEN: ui_manageloginscreen
void ui_manageloginscreen_screen_init(void);
lv_obj_t * ui_manageloginscreen;


// SCREEN: ui_orderscreen2
void ui_orderscreen2_screen_init(void);
lv_obj_t * ui_orderscreen2;
lv_obj_t * ui_Container3;
lv_obj_t * ui_number8container1;
lv_obj_t * ui_number8Image1;
lv_obj_t * ui_number8infcontainer1;
lv_obj_t * ui_number8ImgButtonleft1;
lv_obj_t * ui_number8label3;
lv_obj_t * ui_number8label4;
lv_obj_t * ui_number8ImgButtonright1;
lv_obj_t * ui_number7container1;
lv_obj_t * ui_number7Image1;
lv_obj_t * ui_number7infcontainer1;
lv_obj_t * ui_number7ImgButtonleft1;
lv_obj_t * ui_number7label3;
lv_obj_t * ui_number7label4;
lv_obj_t * ui_number7ImgButtonright1;
lv_obj_t * ui_number6container1;
lv_obj_t * ui_number6Image1;
lv_obj_t * ui_number6infcontainer1;
lv_obj_t * ui_number6ImgButtonleft1;
lv_obj_t * ui_number6label3;
lv_obj_t * ui_number6label4;
lv_obj_t * ui_number6ImgButtonright1;
lv_obj_t * ui_number5container1;
lv_obj_t * ui_number5Image1;
lv_obj_t * ui_number5infcontainer1;
lv_obj_t * ui_number5ImgButtonleft1;
lv_obj_t * ui_number5label3;
lv_obj_t * ui_number5label4;
lv_obj_t * ui_number5ImgButtonright1;
lv_obj_t * ui_number4container1;
lv_obj_t * ui_number4Image1;
lv_obj_t * ui_number4infcontainer1;
lv_obj_t * ui_number4ImgButtonleft1;
lv_obj_t * ui_number4label3;
lv_obj_t * ui_number4label4;
lv_obj_t * ui_number4ImgButtonright1;
lv_obj_t * ui_number3container1;
lv_obj_t * ui_number3Image1;
lv_obj_t * ui_number3infcontainer1;
lv_obj_t * ui_number3ImgButtonleft1;
lv_obj_t * ui_number3label3;
lv_obj_t * ui_number3label4;
lv_obj_t * ui_number3ImgButtonright1;
lv_obj_t * ui_number2container1;
lv_obj_t * ui_number2Image1;
lv_obj_t * ui_number2infcontainer1;
lv_obj_t * ui_number2ImgButtonleft1;
lv_obj_t * ui_number2label3;
lv_obj_t * ui_number2label4;
lv_obj_t * ui_number2ImgButtonright1;
lv_obj_t * ui_number1container1;
lv_obj_t * ui_number1Image1;
lv_obj_t * ui_number1infcontainer1;
lv_obj_t * ui_number1ImgButtonleft1;
lv_obj_t * ui_number1label3;
lv_obj_t * ui_number1label4;
lv_obj_t * ui_number1ImgButtonright1;
lv_obj_t * ui_Container5;
void ui_event_lastpageButton2(lv_event_t * e);
lv_obj_t * ui_lastpageButton2;
lv_obj_t * ui_nextpageButton1;
void ui_event_backButton2(lv_event_t * e);
lv_obj_t * ui_backButton2;
lv_obj_t * ui_confirmButton2;
lv_obj_t * ui_confirmLabel2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void iop_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame);
    lv_anim_set_values(&PropertyAnimation_0, 0, 512);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_orderscreen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_orderscreen1_screen_init);
    }
}
void ui_event_barLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_arc_set_text_value(ui_barLabel, target, "", "");
    }
}
void ui_event_Dropdown3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_screen_change(&ui_orderscreen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_orderscreen1_screen_init);
    }
}
void ui_event_nextpageButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_orderscreen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_orderscreen2_screen_init);
    }
}
void ui_event_backButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_helloscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_helloscreen_screen_init);
    }
}
void ui_event_lastpageButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_orderscreen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_orderscreen1_screen_init);
    }
}
void ui_event_backButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_helloscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_helloscreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_helloscreen_screen_init();
    ui_viplogin_screen_init();
    ui_orderscreen1_screen_init();
    ui_manageloginscreen_screen_init();
    ui_orderscreen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_helloscreen);
}
