// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void iop_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_helloscreen
void ui_helloscreen_screen_init(void);
lv_obj_t * ui_helloscreen;
lv_obj_t * ui_Container1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_bar1;
void ui_event_barLabel(lv_event_t * e);
lv_obj_t * ui_barLabel;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;


// SCREEN: ui_order1
void ui_order1_screen_init(void);
lv_obj_t * ui_order1;
lv_obj_t * ui_Container6;
lv_obj_t * ui_number10;
lv_obj_t * ui_Imagenumber10;
lv_obj_t * ui_infcontainernumber10;
lv_obj_t * ui_ImgButtonleftnumber10;
lv_obj_t * ui_label1number10;
lv_obj_t * ui_label2number10;
lv_obj_t * ui_ImgButtonrightnumber10;
lv_obj_t * ui_number9;
lv_obj_t * ui_Imagenumbe9;
lv_obj_t * ui_infcontainernumber9;
lv_obj_t * ui_ImgButtonleftnumber9;
lv_obj_t * ui_label1number9;
lv_obj_t * ui_label2number9;
lv_obj_t * ui_ImgButtonrightnumber9;
lv_obj_t * ui_number8;
lv_obj_t * ui_Imagenumber8;
lv_obj_t * ui_infcontainernumber8;
lv_obj_t * ui_ImgButtonleftnumber8;
lv_obj_t * ui_label1number8;
lv_obj_t * ui_label2number8;
lv_obj_t * ui_ImgButtonrightnumber8;
lv_obj_t * ui_number7;
lv_obj_t * ui_Imagenumber7;
lv_obj_t * ui_infcontainernumber7;
lv_obj_t * ui_ImgButtonleftnumber7;
lv_obj_t * ui_label1number7;
lv_obj_t * ui_label2number7;
lv_obj_t * ui_ImgButtonrightnumber7;
lv_obj_t * ui_number6;
lv_obj_t * ui_Imagenumber6;
lv_obj_t * ui_infcontainernumber6;
lv_obj_t * ui_ImgButtonleftnumber6;
lv_obj_t * ui_label1number6;
lv_obj_t * ui_label2number6;
lv_obj_t * ui_ImgButtonrightnumber6;
lv_obj_t * ui_number5;
lv_obj_t * ui_Imagenumber5;
lv_obj_t * ui_infcontainernumber5;
lv_obj_t * ui_ImgButtonleftnumber5;
lv_obj_t * ui_label1number5;
lv_obj_t * ui_label2number5;
lv_obj_t * ui_ImgButtonrightnumber5;
lv_obj_t * ui_number4;
lv_obj_t * ui_Imagenumber4;
lv_obj_t * ui_infcontainernumber4;
lv_obj_t * ui_ImgButtonleftnumber4;
lv_obj_t * ui_label5number4;
lv_obj_t * ui_label1number4;
lv_obj_t * ui_ImgButtonright3number4;
lv_obj_t * ui_number3;
lv_obj_t * ui_Imagenumber3;
lv_obj_t * ui_infcontainernumber3;
lv_obj_t * ui_ImgButtonleftnumber3;
lv_obj_t * ui_labelnumber3;
lv_obj_t * ui_label1number3;
lv_obj_t * ui_ImgButtonrightnumber3;
lv_obj_t * ui_number2;
lv_obj_t * ui_Imagenumber2;
lv_obj_t * ui_infcontainernumber2;
lv_obj_t * ui_ImgButtonleftnumber2;
lv_obj_t * ui_label1number2;
lv_obj_t * ui_label2number2;
lv_obj_t * ui_ImgButtonrightnumber2;
lv_obj_t * ui_number1;
lv_obj_t * ui_Imagenumber1;
lv_obj_t * ui_infcontainernumber1;
lv_obj_t * ui_ImgButtonleftnumber1;
lv_obj_t * ui_label1number1;
lv_obj_t * ui_label2number1;
lv_obj_t * ui_ImgButtonrightnumber1;
void ui_event_ImgButton1(lv_event_t * e);
void ui_event_nextpageButon1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_ImgButton3;
lv_obj_t * ui_Buttonconfirm1;
lv_obj_t * ui_Labelconfirm1;

// SCREEN: ui_order2
void ui_order2_screen_init(void);
lv_obj_t * ui_order2;
lv_obj_t * ui_Container7;
lv_obj_t * ui_number20;
lv_obj_t * ui_Imagenumber20;
lv_obj_t * ui_infcontainernumber20;
lv_obj_t * ui_ImgButtonleftnumber20;
lv_obj_t * ui_label1number20;
lv_obj_t * ui_label2number20;
lv_obj_t * ui_ImgButtonrightnumber20;
lv_obj_t * ui_number19;
lv_obj_t * ui_Imagenumber19;
lv_obj_t * ui_infcontainernumber19;
lv_obj_t * ui_ImgButtonleftnumber19;
lv_obj_t * ui_label1number19;
lv_obj_t * ui_label2number19;
lv_obj_t * ui_ImgButtonrightnumber19;
lv_obj_t * ui_number18;
lv_obj_t * ui_Imagenumber18;
lv_obj_t * ui_infcontainernumber18;
lv_obj_t * ui_ImgButtonleftnumber18;
lv_obj_t * ui_labelnumber18;
lv_obj_t * ui_label1number18;
lv_obj_t * ui_ImgButtonrightnumber18;
lv_obj_t * ui_number17;
lv_obj_t * ui_Imagenumber17;
lv_obj_t * ui_infcontainernumber17;
lv_obj_t * ui_ImgButtonleftnumber17;
lv_obj_t * ui_label5number17;
lv_obj_t * ui_label1number17;
lv_obj_t * ui_ImgButtonright3number17;
lv_obj_t * ui_number16;
lv_obj_t * ui_Imagenumber16;
lv_obj_t * ui_infcontainernumber16;
lv_obj_t * ui_ImgButtonleftnumber16;
lv_obj_t * ui_label1number16;
lv_obj_t * ui_label2number16;
lv_obj_t * ui_ImgButtonrightnumber16;
lv_obj_t * ui_number15;
lv_obj_t * ui_Imagenumber15;
lv_obj_t * ui_infcontainernumber15;
lv_obj_t * ui_ImgButtonleftnumber15;
lv_obj_t * ui_label1number15;
lv_obj_t * ui_label2number15;
lv_obj_t * ui_ImgButtonrightnumber15;
lv_obj_t * ui_number14;
lv_obj_t * ui_Imagenumber14;
lv_obj_t * ui_infcontainernumber14;
lv_obj_t * ui_ImgButtonleftnumber14;
lv_obj_t * ui_label1number14;
lv_obj_t * ui_label2number14;
lv_obj_t * ui_ImgButtonrightnumber14;
lv_obj_t * ui_number13;
lv_obj_t * ui_Imagenumber13;
lv_obj_t * ui_infcontainernumber13;
lv_obj_t * ui_ImgButtonleftnumber13;
lv_obj_t * ui_label1number13;
lv_obj_t * ui_label2number13;
lv_obj_t * ui_ImgButtonrightnumber13;
lv_obj_t * ui_number12;
lv_obj_t * ui_Imagenumbe12;
lv_obj_t * ui_infcontainernumber12;
lv_obj_t * ui_ImgButtonleftnumber12;
lv_obj_t * ui_label1number12;
lv_obj_t * ui_label2number12;
lv_obj_t * ui_ImgButtonrightnumber12;
lv_obj_t * ui_number11;
lv_obj_t * ui_Imagenumber11;
lv_obj_t * ui_infcontainernumber11;
lv_obj_t * ui_ImgButtonleftnumber11;
lv_obj_t * ui_label1number11;
lv_obj_t * ui_label2number11;
lv_obj_t * ui_ImgButtonrightnumber11;
void ui_event_lastpageButon2(lv_event_t * e);
void ui_event_nextpageButon2(lv_event_t * e);
lv_obj_t * ui_lastpageButon2;
lv_obj_t * ui_nextpageButon2;
lv_obj_t * ui_backButton3;
lv_obj_t * ui____initial_actions0;

// SCREEN: ui_login
void ui_login_screen_init(void);
lv_obj_t * ui_login;
lv_obj_t * ui_TabView1;
void ui_event_TabPage1(lv_event_t * e);
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_Container2;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_Buttonsignup1;
lv_obj_t * ui_Labelsignup1;
lv_obj_t * ui_Buttonlogin1;
lv_obj_t * ui_Labellogin1;
void ui_event_TabPage2(lv_event_t * e);
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_Container3;
void ui_event_TextArea3(lv_event_t * e);
lv_obj_t * ui_TextArea3;
void ui_event_TextArea4(lv_event_t * e);
lv_obj_t * ui_TextArea4;
lv_obj_t * ui_Buttonsignup2;
lv_obj_t * ui_Labelsignup2;
lv_obj_t * ui_Buttonlogin2;
lv_obj_t * ui_Labellogin2;
void ui_event_TabPage3(lv_event_t * e);
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_Container5;
void ui_event_TextArea5(lv_event_t * e);
lv_obj_t * ui_TextArea5;
void ui_event_TextArea6(lv_event_t * e);
lv_obj_t * ui_TextArea6;
lv_obj_t * ui_Buttonsignup3;
lv_obj_t * ui_Labelsignup3;
lv_obj_t * ui_Buttonlogin3;
lv_obj_t * ui_Labellogin3;
lv_obj_t * ui_Keyboard1;
void ui_event_ImgButton5(lv_event_t * e);
lv_obj_t * ui_ImgButton5;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void iop_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame);
    lv_anim_set_values(&PropertyAnimation_0, 0, 512);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_order1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_order1_screen_init);
    }
}

void ui_event_nextpageButon1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_order2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_order2_screen_init);
    }
}

void ui_event_lastpageButon2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_order1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_order1_screen_init);
    }
}

// void ui_event_nextpageButon2(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_order3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_order1_screen_init);
//     }
// }

void ui_event_barLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_arc_set_text_value(ui_barLabel, target, "", "");
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_login, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_login_screen_init);
    }
}
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_helloscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_helloscreen_screen_init);
    }
}
void ui_event_TabPage1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea2);
    }
}
void ui_event_TabPage2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea3);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_TextArea4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea4);
    }
}
void ui_event_TabPage3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TextArea5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea5);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_TextArea6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea6);
    }
}
void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_helloscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_helloscreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_helloscreen_screen_init();
    ui_order1_screen_init();
    ui_login_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_helloscreen);
}
