// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#ifndef _TEST1_UI_H
#define _TEST1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void iop_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_helloscreen
void ui_helloscreen_screen_init(void);
extern lv_obj_t * ui_helloscreen;
extern lv_obj_t * ui_Container1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_bar1;
void ui_event_barLabel(lv_event_t * e);
extern lv_obj_t * ui_barLabel;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_order1
void ui_order1_screen_init(void);
extern lv_obj_t * ui_order1;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_number10;
extern lv_obj_t * ui_Imagenumber10;
extern lv_obj_t * ui_infcontainernumber10;
extern lv_obj_t * ui_ImgButtonleftnumber10;
extern lv_obj_t * ui_label1number10;
extern lv_obj_t * ui_label2number10;
extern lv_obj_t * ui_ImgButtonrightnumber10;
extern lv_obj_t * ui_number9;
extern lv_obj_t * ui_Imagenumbe9;
extern lv_obj_t * ui_infcontainernumber9;
extern lv_obj_t * ui_ImgButtonleftnumber9;
extern lv_obj_t * ui_label1number9;
extern lv_obj_t * ui_label2number9;
extern lv_obj_t * ui_ImgButtonrightnumber9;
extern lv_obj_t * ui_number8;
extern lv_obj_t * ui_Imagenumber8;
extern lv_obj_t * ui_infcontainernumber8;
extern lv_obj_t * ui_ImgButtonleftnumber8;
extern lv_obj_t * ui_label1number8;
extern lv_obj_t * ui_label2number8;
extern lv_obj_t * ui_ImgButtonrightnumber8;
extern lv_obj_t * ui_number7;
extern lv_obj_t * ui_Imagenumber7;
extern lv_obj_t * ui_infcontainernumber7;
extern lv_obj_t * ui_ImgButtonleftnumber7;
extern lv_obj_t * ui_label1number7;
extern lv_obj_t * ui_label2number7;
extern lv_obj_t * ui_ImgButtonrightnumber7;
extern lv_obj_t * ui_number6;
extern lv_obj_t * ui_Imagenumber6;
extern lv_obj_t * ui_infcontainernumber6;
extern lv_obj_t * ui_ImgButtonleftnumber6;
extern lv_obj_t * ui_label1number6;
extern lv_obj_t * ui_label2number6;
extern lv_obj_t * ui_ImgButtonrightnumber6;
extern lv_obj_t * ui_number5;
extern lv_obj_t * ui_Imagenumber5;
extern lv_obj_t * ui_infcontainernumber5;
extern lv_obj_t * ui_ImgButtonleftnumber5;
extern lv_obj_t * ui_label1number5;
extern lv_obj_t * ui_label2number5;
extern lv_obj_t * ui_ImgButtonrightnumber5;
extern lv_obj_t * ui_number4;
extern lv_obj_t * ui_Imagenumber4;
extern lv_obj_t * ui_infcontainernumber4;
extern lv_obj_t * ui_ImgButtonleftnumber4;
extern lv_obj_t * ui_label5number4;
extern lv_obj_t * ui_label1number4;
extern lv_obj_t * ui_ImgButtonright3number4;
extern lv_obj_t * ui_number3;
extern lv_obj_t * ui_Imagenumber3;
extern lv_obj_t * ui_infcontainernumber3;
extern lv_obj_t * ui_ImgButtonleftnumber3;
extern lv_obj_t * ui_labelnumber3;
extern lv_obj_t * ui_label1number3;
extern lv_obj_t * ui_ImgButtonrightnumber3;
extern lv_obj_t * ui_number2;
extern lv_obj_t * ui_Imagenumber2;
extern lv_obj_t * ui_infcontainernumber2;
extern lv_obj_t * ui_ImgButtonleftnumber2;
extern lv_obj_t * ui_label1number2;
extern lv_obj_t * ui_label2number2;
extern lv_obj_t * ui_ImgButtonrightnumber2;
extern lv_obj_t * ui_number1;
extern lv_obj_t * ui_Imagenumber1;
extern lv_obj_t * ui_infcontainernumber1;
extern lv_obj_t * ui_ImgButtonleftnumber1;
extern lv_obj_t * ui_label1number1;
extern lv_obj_t * ui_label2number1;
extern lv_obj_t * ui_ImgButtonrightnumber1;
void ui_event_ImgButton1(lv_event_t * e);
void ui_event_nextpageButon1(lv_event_t * e);
extern lv_obj_t * ui_lastpageButon1;
extern lv_obj_t * ui_nextpageButon1;
extern lv_obj_t * ui_backButton2;
// extern lv_obj_t * ui_ImgButton1;
// extern lv_obj_t * ui_ImgButton2;
// extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Buttonconfirm1;
extern lv_obj_t * ui_Labelconfirm1;
// SCREEN: ui_order2
void ui_order2_screen_init(void);
extern lv_obj_t * ui_order2;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_number20;
extern lv_obj_t * ui_Imagenumber20;
extern lv_obj_t * ui_infcontainernumber20;
extern lv_obj_t * ui_ImgButtonleftnumber20;
extern lv_obj_t * ui_label1number20;
extern lv_obj_t * ui_label2number20;
extern lv_obj_t * ui_ImgButtonrightnumber20;
extern lv_obj_t * ui_number19;
extern lv_obj_t * ui_Imagenumber19;
extern lv_obj_t * ui_infcontainernumber19;
extern lv_obj_t * ui_ImgButtonleftnumber19;
extern lv_obj_t * ui_label1number19;
extern lv_obj_t * ui_label2number19;
extern lv_obj_t * ui_ImgButtonrightnumber19;
extern lv_obj_t * ui_number18;
extern lv_obj_t * ui_Imagenumber18;
extern lv_obj_t * ui_infcontainernumber18;
extern lv_obj_t * ui_ImgButtonleftnumber18;
extern lv_obj_t * ui_labelnumber18;
extern lv_obj_t * ui_label1number18;
extern lv_obj_t * ui_ImgButtonrightnumber18;
extern lv_obj_t * ui_number17;
extern lv_obj_t * ui_Imagenumber17;
extern lv_obj_t * ui_infcontainernumber17;
extern lv_obj_t * ui_ImgButtonleftnumber17;
extern lv_obj_t * ui_label5number17;
extern lv_obj_t * ui_label1number17;
extern lv_obj_t * ui_ImgButtonright3number17;
extern lv_obj_t * ui_number16;
extern lv_obj_t * ui_Imagenumber16;
extern lv_obj_t * ui_infcontainernumber16;
extern lv_obj_t * ui_ImgButtonleftnumber16;
extern lv_obj_t * ui_label1number16;
extern lv_obj_t * ui_label2number16;
extern lv_obj_t * ui_ImgButtonrightnumber16;
extern lv_obj_t * ui_number15;
extern lv_obj_t * ui_Imagenumber15;
extern lv_obj_t * ui_infcontainernumber15;
extern lv_obj_t * ui_ImgButtonleftnumber15;
extern lv_obj_t * ui_label1number15;
extern lv_obj_t * ui_label2number15;
extern lv_obj_t * ui_ImgButtonrightnumber15;
extern lv_obj_t * ui_number14;
extern lv_obj_t * ui_Imagenumber14;
extern lv_obj_t * ui_infcontainernumber14;
extern lv_obj_t * ui_ImgButtonleftnumber14;
extern lv_obj_t * ui_label1number14;
extern lv_obj_t * ui_label2number14;
extern lv_obj_t * ui_ImgButtonrightnumber14;
extern lv_obj_t * ui_number13;
extern lv_obj_t * ui_Imagenumber13;
extern lv_obj_t * ui_infcontainernumber13;
extern lv_obj_t * ui_ImgButtonleftnumber13;
extern lv_obj_t * ui_label1number13;
extern lv_obj_t * ui_label2number13;
extern lv_obj_t * ui_ImgButtonrightnumber13;
extern lv_obj_t * ui_number12;
extern lv_obj_t * ui_Imagenumbe12;
extern lv_obj_t * ui_infcontainernumber12;
extern lv_obj_t * ui_ImgButtonleftnumber12;
extern lv_obj_t * ui_label1number12;
extern lv_obj_t * ui_label2number12;
extern lv_obj_t * ui_ImgButtonrightnumber12;
extern lv_obj_t * ui_number11;
extern lv_obj_t * ui_Imagenumber11;
extern lv_obj_t * ui_infcontainernumber11;
extern lv_obj_t * ui_ImgButtonleftnumber11;
extern lv_obj_t * ui_label1number11;
extern lv_obj_t * ui_label2number11;
extern lv_obj_t * ui_ImgButtonrightnumber11;
void ui_event_lastpageButon2(lv_event_t * e);
void ui_event_nextpageButon2(lv_event_t * e);
extern lv_obj_t * ui_lastpageButon2;
extern lv_obj_t * ui_nextpageButon2;
extern lv_obj_t * ui_backButton3;
extern lv_obj_t * ui____initial_actions0;
// SCREEN: ui_login
void ui_login_screen_init(void);
extern lv_obj_t * ui_login;
extern lv_obj_t * ui_TabView1;
void ui_event_TabPage1(lv_event_t * e);
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Container2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Buttonsignup1;
extern lv_obj_t * ui_Labelsignup1;
extern lv_obj_t * ui_Buttonlogin1;
extern lv_obj_t * ui_Labellogin1;
void ui_event_TabPage2(lv_event_t * e);
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Container3;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
void ui_event_TextArea4(lv_event_t * e);
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_Buttonsignup2;
extern lv_obj_t * ui_Labelsignup2;
extern lv_obj_t * ui_Buttonlogin2;
extern lv_obj_t * ui_Labellogin2;
void ui_event_TabPage3(lv_event_t * e);
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Container5;
void ui_event_TextArea5(lv_event_t * e);
extern lv_obj_t * ui_TextArea5;
void ui_event_TextArea6(lv_event_t * e);
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_Buttonsignup3;
extern lv_obj_t * ui_Labelsignup3;
extern lv_obj_t * ui_Buttonlogin3;
extern lv_obj_t * ui_Labellogin3;
extern lv_obj_t * ui_Keyboard1;
void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_1485140228);    // assets/背景图.png
LV_IMG_DECLARE(ui_img_1119412587);    // assets/番茄牛肉.png
LV_IMG_DECLARE(ui_img_221393495);    // assets/减号.png
LV_IMG_DECLARE(ui_img_1284172916);    // assets/加号.png
LV_IMG_DECLARE(ui_img_412946995);    // assets/小炒肉.png
LV_IMG_DECLARE(ui_img_1143013810);    // assets/剁椒皮皮虾.png
LV_IMG_DECLARE(ui_img_682017832);    // assets/鱼香肉丝.png
LV_IMG_DECLARE(ui_img_1926326647);    // assets/回锅肉.png
LV_IMG_DECLARE(ui_img_734771989);    // assets/翡翠虾仁.png
LV_IMG_DECLARE(ui_img_1855500935);    // assets/宫保鸡丁.png
LV_IMG_DECLARE(ui_img_293691247);    // assets/秘制红烧肉.png
LV_IMG_DECLARE(ui_img_1341173067);    // assets/新回锅肉.png
LV_IMG_DECLARE(ui_img_2092529074);    // assets/红烧鲈鱼.png
LV_IMG_DECLARE(ui_img_lastpage_png);    // assets/lastpage.png
LV_IMG_DECLARE(ui_img_nextpage_png);    // assets/nextpage.png
LV_IMG_DECLARE(ui_img_1609717271);    // assets/返回.png
LV_IMG_DECLARE(ui_img_814352610);    // assets/猪肉炖粉条.png
LV_IMG_DECLARE(ui_img_1429700948);    // assets/番茄炒蛋.png
LV_IMG_DECLARE(ui_img_403749227);    // assets/紫苏田螺.png
LV_IMG_DECLARE(ui_img_784203148);    // assets/红烧带鱼.png
LV_IMG_DECLARE(ui_img_462669028);    // assets/红烧排骨.png
LV_IMG_DECLARE(ui_img_1181513690);    // assets/红烧狮子头.png
LV_IMG_DECLARE(ui_img_139154128);    // assets/锅包肉.png
LV_IMG_DECLARE(ui_img_2035788098);    // assets/麻婆豆腐.png



LV_FONT_DECLARE(ui_font_chinese20);
LV_FONT_DECLARE(ui_font_chinese30);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
