// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#ifndef _TEST1_UI_H
#define _TEST1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void iop_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_helloscreen
void ui_helloscreen_screen_init(void);
extern lv_obj_t * ui_helloscreen;
extern lv_obj_t * ui_Container1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_bar1;
void ui_event_barLabel(lv_event_t * e);
extern lv_obj_t * ui_barLabel;
void ui_event_Dropdown3(lv_event_t * e);
extern lv_obj_t * ui_Dropdown3;
// SCREEN: ui_viplogin
void ui_viplogin_screen_init(void);
extern lv_obj_t * ui_viplogin;
// SCREEN: ui_orderscreen1
void ui_orderscreen1_screen_init(void);
extern lv_obj_t * ui_orderscreen1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_number8container;
extern lv_obj_t * ui_number8Image;
extern lv_obj_t * ui_number8infcontainer;
extern lv_obj_t * ui_number8ImgButtonleft;
extern lv_obj_t * ui_number8label1;
extern lv_obj_t * ui_number8label2;
extern lv_obj_t * ui_number8ImgButtonright;
extern lv_obj_t * ui_number7container;
extern lv_obj_t * ui_number7Image;
extern lv_obj_t * ui_number7infcontainer;
extern lv_obj_t * ui_number7ImgButtonleft;
extern lv_obj_t * ui_number7label1;
extern lv_obj_t * ui_number7label2;
extern lv_obj_t * ui_number7ImgButtonright;
extern lv_obj_t * ui_number6container;
extern lv_obj_t * ui_number6Image;
extern lv_obj_t * ui_number6infcontainer;
extern lv_obj_t * ui_number6ImgButtonleft;
extern lv_obj_t * ui_number6label1;
extern lv_obj_t * ui_number6label2;
extern lv_obj_t * ui_number6ImgButtonright;
extern lv_obj_t * ui_number5container;
extern lv_obj_t * ui_number5Image;
extern lv_obj_t * ui_number5infcontainer;
extern lv_obj_t * ui_number5ImgButtonleft;
extern lv_obj_t * ui_number5label1;
extern lv_obj_t * ui_number5label2;
extern lv_obj_t * ui_number5ImgButtonright;
extern lv_obj_t * ui_number4container;
extern lv_obj_t * ui_number4Image;
extern lv_obj_t * ui_number4infcontainer;
extern lv_obj_t * ui_number4ImgButtonleft;
extern lv_obj_t * ui_number4label1;
extern lv_obj_t * ui_number4label2;
extern lv_obj_t * ui_number4ImgButtonright;
extern lv_obj_t * ui_number3container;
extern lv_obj_t * ui_number3Image;
extern lv_obj_t * ui_number3infcontainer;
extern lv_obj_t * ui_number3ImgButtonleft;
extern lv_obj_t * ui_number3label1;
extern lv_obj_t * ui_number3label2;
extern lv_obj_t * ui_number3ImgButtonright;
extern lv_obj_t * ui_number2container;
extern lv_obj_t * ui_number2Image;
extern lv_obj_t * ui_number2infcontainer;
extern lv_obj_t * ui_number2ImgButtonleft;
extern lv_obj_t * ui_number2label1;
extern lv_obj_t * ui_number2label2;
extern lv_obj_t * ui_number2ImgButtonright;
extern lv_obj_t * ui_number1container;
extern lv_obj_t * ui_number1Image;
extern lv_obj_t * ui_number1infcontainer;
extern lv_obj_t * ui_number1ImgButtonleft;
extern lv_obj_t * ui_number1label1;
extern lv_obj_t * ui_number1label2;
extern lv_obj_t * ui_number1ImgButtonright;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_lastpageButton1;
void ui_event_nextpageButton2(lv_event_t * e);
extern lv_obj_t * ui_nextpageButton2;
void ui_event_backButton1(lv_event_t * e);
extern lv_obj_t * ui_backButton1;
extern lv_obj_t * ui_confirmButton1;
extern lv_obj_t * ui_confirmLabel1;
// SCREEN: ui_manageloginscreen
void ui_manageloginscreen_screen_init(void);
extern lv_obj_t * ui_manageloginscreen;
// SCREEN: ui_orderscreen2
void ui_orderscreen2_screen_init(void);
extern lv_obj_t * ui_orderscreen2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_number8container1;
extern lv_obj_t * ui_number8Image1;
extern lv_obj_t * ui_number8infcontainer1;
extern lv_obj_t * ui_number8ImgButtonleft1;
extern lv_obj_t * ui_number8label3;
extern lv_obj_t * ui_number8label4;
extern lv_obj_t * ui_number8ImgButtonright1;
extern lv_obj_t * ui_number7container1;
extern lv_obj_t * ui_number7Image1;
extern lv_obj_t * ui_number7infcontainer1;
extern lv_obj_t * ui_number7ImgButtonleft1;
extern lv_obj_t * ui_number7label3;
extern lv_obj_t * ui_number7label4;
extern lv_obj_t * ui_number7ImgButtonright1;
extern lv_obj_t * ui_number6container1;
extern lv_obj_t * ui_number6Image1;
extern lv_obj_t * ui_number6infcontainer1;
extern lv_obj_t * ui_number6ImgButtonleft1;
extern lv_obj_t * ui_number6label3;
extern lv_obj_t * ui_number6label4;
extern lv_obj_t * ui_number6ImgButtonright1;
extern lv_obj_t * ui_number5container1;
extern lv_obj_t * ui_number5Image1;
extern lv_obj_t * ui_number5infcontainer1;
extern lv_obj_t * ui_number5ImgButtonleft1;
extern lv_obj_t * ui_number5label3;
extern lv_obj_t * ui_number5label4;
extern lv_obj_t * ui_number5ImgButtonright1;
extern lv_obj_t * ui_number4container1;
extern lv_obj_t * ui_number4Image1;
extern lv_obj_t * ui_number4infcontainer1;
extern lv_obj_t * ui_number4ImgButtonleft1;
extern lv_obj_t * ui_number4label3;
extern lv_obj_t * ui_number4label4;
extern lv_obj_t * ui_number4ImgButtonright1;
extern lv_obj_t * ui_number3container1;
extern lv_obj_t * ui_number3Image1;
extern lv_obj_t * ui_number3infcontainer1;
extern lv_obj_t * ui_number3ImgButtonleft1;
extern lv_obj_t * ui_number3label3;
extern lv_obj_t * ui_number3label4;
extern lv_obj_t * ui_number3ImgButtonright1;
extern lv_obj_t * ui_number2container1;
extern lv_obj_t * ui_number2Image1;
extern lv_obj_t * ui_number2infcontainer1;
extern lv_obj_t * ui_number2ImgButtonleft1;
extern lv_obj_t * ui_number2label3;
extern lv_obj_t * ui_number2label4;
extern lv_obj_t * ui_number2ImgButtonright1;
extern lv_obj_t * ui_number1container1;
extern lv_obj_t * ui_number1Image1;
extern lv_obj_t * ui_number1infcontainer1;
extern lv_obj_t * ui_number1ImgButtonleft1;
extern lv_obj_t * ui_number1label3;
extern lv_obj_t * ui_number1label4;
extern lv_obj_t * ui_number1ImgButtonright1;
extern lv_obj_t * ui_Container5;
void ui_event_lastpageButton2(lv_event_t * e);
extern lv_obj_t * ui_lastpageButton2;
extern lv_obj_t * ui_nextpageButton1;
void ui_event_backButton2(lv_event_t * e);
extern lv_obj_t * ui_backButton2;
extern lv_obj_t * ui_confirmButton2;
extern lv_obj_t * ui_confirmLabel2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_1852348671);    // assets/欢迎.png
LV_IMG_DECLARE(ui_img_1485140228);    // assets/背景图.png
LV_IMG_DECLARE(ui_img_1429700948);    // assets/番茄炒蛋.png
LV_IMG_DECLARE(ui_img_221393495);    // assets/减号.png
LV_IMG_DECLARE(ui_img_1284172916);    // assets/加号.png
LV_IMG_DECLARE(ui_img_682017832);    // assets/鱼香肉丝.png
LV_IMG_DECLARE(ui_img_1926326647);    // assets/回锅肉.png
LV_IMG_DECLARE(ui_img_1341173067);    // assets/新回锅肉.png
LV_IMG_DECLARE(ui_img_293691247);    // assets/秘制红烧肉.png
LV_IMG_DECLARE(ui_img_734771989);    // assets/翡翠虾仁.png
LV_IMG_DECLARE(ui_img_1855500935);    // assets/宫保鸡丁.png
LV_IMG_DECLARE(ui_img_2092529074);    // assets/红烧鲈鱼.png
LV_IMG_DECLARE(ui_img_lastpage_png);    // assets/lastpage.png
LV_IMG_DECLARE(ui_img_nextpage_png);    // assets/nextpage.png
LV_IMG_DECLARE(ui_img_1609717271);    // assets/返回.png
LV_IMG_DECLARE(ui_img_112040420);    // assets/土豆炖牛肉.png
LV_IMG_DECLARE(ui_img_403749227);    // assets/紫苏田螺.png
LV_IMG_DECLARE(ui_img_1181513690);    // assets/红烧狮子头.png
LV_IMG_DECLARE(ui_img_139154128);    // assets/锅包肉.png
LV_IMG_DECLARE(ui_img_1119412587);    // assets/番茄牛肉.png
LV_IMG_DECLARE(ui_img_1143013810);    // assets/剁椒皮皮虾.png
LV_IMG_DECLARE(ui_img_412946995);    // assets/小炒肉.png
LV_IMG_DECLARE(ui_img_814352610);    // assets/猪肉炖粉条.png



LV_FONT_DECLARE(ui_font_chinese30);
LV_FONT_DECLARE(ui_font_chinese20);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
