// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#include "../ui.h"

void ui_manageloginscreen_screen_init(void)
{
    ui_manageloginscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_manageloginscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_manageloginscreen, &ui_img_1485140228, LV_PART_MAIN | LV_STATE_DEFAULT);


}
