// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#include "../ui.h"

void ui_helloscreen_screen_init(void)
{
    ui_helloscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_helloscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_helloscreen, &ui_img_1852348671, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_helloscreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 833);
    lv_obj_set_height(ui_Container1, 218);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 140);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button1, 300);
    lv_obj_set_height(ui_Button1, 90);
    lv_obj_set_x(ui_Button1, 181);
    lv_obj_set_y(ui_Button1, -59);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x99CCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0x6699FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "查看菜单");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar1 = lv_bar_create(ui_Container1);
    lv_obj_set_width(ui_bar1, 300);
    lv_obj_set_height(ui_bar1, 10);
    lv_obj_set_x(ui_bar1, -8);
    lv_obj_set_y(ui_bar1, 89);
    lv_obj_set_align(ui_bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_anim_time(ui_bar1, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barLabel = lv_label_create(ui_bar1);
    lv_obj_set_width(ui_barLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_barLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_barLabel, 127);
    lv_obj_set_y(ui_barLabel, 0);
    lv_obj_set_align(ui_barLabel, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_barLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_barLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button2, 300);
    lv_obj_set_height(ui_Button2, 90);
    lv_obj_set_x(ui_Button2, -191);
    lv_obj_set_y(ui_Button2, -58);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x99CCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button2, lv_color_hex(0x6699FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "登录");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_barLabel, ui_event_barLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}
