// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#include "../ui.h"

void ui_order1_screen_init(void)
{
    ui_order1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_order1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_order1, &ui_img_1485140228, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_order1);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 1024);
    lv_obj_set_height(ui_Container6, 400);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, -100);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number10 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number10);
    lv_obj_set_width(ui_number10, 200);
    lv_obj_set_height(ui_number10, 200);
    lv_obj_set_x(ui_number10, -716);
    lv_obj_set_y(ui_number10, -186);
    lv_obj_set_align(ui_number10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber10 = lv_img_create(ui_number10);
    lv_img_set_src(ui_Imagenumber10, &ui_img_1119412587);
    lv_obj_set_width(ui_Imagenumber10, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber10, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber10, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber10 = lv_obj_create(ui_number10);
    lv_obj_remove_style_all(ui_infcontainernumber10);
    lv_obj_set_width(ui_infcontainernumber10, 200);
    lv_obj_set_height(ui_infcontainernumber10, 80);
    lv_obj_set_align(ui_infcontainernumber10, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber10 = lv_imgbtn_create(ui_infcontainernumber10);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber10, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber10, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber10, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber10, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber10, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber10, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber10, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber10, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber10, 4);

    ui_label1number10 = lv_label_create(ui_infcontainernumber10);
    lv_obj_set_width(ui_label1number10, 129);
    lv_obj_set_height(ui_label1number10, 50);
    lv_obj_set_x(ui_label1number10, 3);
    lv_obj_set_y(ui_label1number10, -12);
    lv_obj_set_align(ui_label1number10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number10, "番茄牛肉17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number10, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number10 = lv_label_create(ui_infcontainernumber10);
    lv_obj_set_width(ui_label2number10, 129);
    lv_obj_set_height(ui_label2number10, 20);
    lv_obj_set_x(ui_label2number10, 3);
    lv_obj_set_y(ui_label2number10, 23);
    lv_obj_set_align(ui_label2number10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number10, "已购买");
    lv_obj_set_style_text_font(ui_label2number10, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber10 = lv_imgbtn_create(ui_infcontainernumber10);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber10, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber10, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber10, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber10, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber10, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber10, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber10, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber10, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber10, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber10, LV_ALIGN_CENTER);

    ui_number9 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number9);
    lv_obj_set_width(ui_number9, 200);
    lv_obj_set_height(ui_number9, 200);
    lv_obj_set_x(ui_number9, -716);
    lv_obj_set_y(ui_number9, -186);
    lv_obj_set_align(ui_number9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumbe9 = lv_img_create(ui_number9);
    lv_img_set_src(ui_Imagenumbe9, &ui_img_412946995);
    lv_obj_set_width(ui_Imagenumbe9, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumbe9, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumbe9, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumbe9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumbe9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber9 = lv_obj_create(ui_number9);
    lv_obj_remove_style_all(ui_infcontainernumber9);
    lv_obj_set_width(ui_infcontainernumber9, 200);
    lv_obj_set_height(ui_infcontainernumber9, 80);
    lv_obj_set_align(ui_infcontainernumber9, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber9 = lv_imgbtn_create(ui_infcontainernumber9);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber9, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber9, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber9, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber9, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber9, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber9, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber9, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber9, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber9, 4);

    ui_label1number9 = lv_label_create(ui_infcontainernumber9);
    lv_obj_set_width(ui_label1number9, 129);
    lv_obj_set_height(ui_label1number9, 50);
    lv_obj_set_x(ui_label1number9, 3);
    lv_obj_set_y(ui_label1number9, -12);
    lv_obj_set_align(ui_label1number9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number9, "小炒肉17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number9, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number9 = lv_label_create(ui_infcontainernumber9);
    lv_obj_set_width(ui_label2number9, 129);
    lv_obj_set_height(ui_label2number9, 20);
    lv_obj_set_x(ui_label2number9, 3);
    lv_obj_set_y(ui_label2number9, 23);
    lv_obj_set_align(ui_label2number9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number9, "已购买");
    lv_obj_set_style_text_font(ui_label2number9, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber9 = lv_imgbtn_create(ui_infcontainernumber9);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber9, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber9, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber9, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber9, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber9, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber9, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber9, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber9, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber9, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber9, LV_ALIGN_CENTER);

    ui_number8 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number8);
    lv_obj_set_width(ui_number8, 200);
    lv_obj_set_height(ui_number8, 200);
    lv_obj_set_x(ui_number8, -716);
    lv_obj_set_y(ui_number8, -186);
    lv_obj_set_align(ui_number8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber8 = lv_img_create(ui_number8);
    lv_img_set_src(ui_Imagenumber8, &ui_img_1143013810);
    lv_obj_set_width(ui_Imagenumber8, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber8, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber8, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber8 = lv_obj_create(ui_number8);
    lv_obj_remove_style_all(ui_infcontainernumber8);
    lv_obj_set_width(ui_infcontainernumber8, 200);
    lv_obj_set_height(ui_infcontainernumber8, 80);
    lv_obj_set_align(ui_infcontainernumber8, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber8 = lv_imgbtn_create(ui_infcontainernumber8);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber8, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber8, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber8, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber8, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber8, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber8, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber8, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber8, 4);

    ui_label1number8 = lv_label_create(ui_infcontainernumber8);
    lv_obj_set_width(ui_label1number8, 129);
    lv_obj_set_height(ui_label1number8, 50);
    lv_obj_set_x(ui_label1number8, 3);
    lv_obj_set_y(ui_label1number8, -12);
    lv_obj_set_align(ui_label1number8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number8, "剁椒皮皮虾17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number8, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number8 = lv_label_create(ui_infcontainernumber8);
    lv_obj_set_width(ui_label2number8, 129);
    lv_obj_set_height(ui_label2number8, 20);
    lv_obj_set_x(ui_label2number8, 3);
    lv_obj_set_y(ui_label2number8, 23);
    lv_obj_set_align(ui_label2number8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number8, "已购买");
    lv_obj_set_style_text_font(ui_label2number8, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber8 = lv_imgbtn_create(ui_infcontainernumber8);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber8, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber8, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber8, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber8, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber8, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber8, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber8, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber8, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber8, LV_ALIGN_CENTER);

    ui_number7 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number7);
    lv_obj_set_width(ui_number7, 200);
    lv_obj_set_height(ui_number7, 200);
    lv_obj_set_x(ui_number7, -716);
    lv_obj_set_y(ui_number7, -186);
    lv_obj_set_align(ui_number7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber7 = lv_img_create(ui_number7);
    lv_img_set_src(ui_Imagenumber7, &ui_img_682017832);
    lv_obj_set_width(ui_Imagenumber7, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber7, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber7, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber7 = lv_obj_create(ui_number7);
    lv_obj_remove_style_all(ui_infcontainernumber7);
    lv_obj_set_width(ui_infcontainernumber7, 200);
    lv_obj_set_height(ui_infcontainernumber7, 80);
    lv_obj_set_align(ui_infcontainernumber7, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber7 = lv_imgbtn_create(ui_infcontainernumber7);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber7, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber7, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber7, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber7, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber7, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber7, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber7, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber7, 4);

    ui_label1number7 = lv_label_create(ui_infcontainernumber7);
    lv_obj_set_width(ui_label1number7, 129);
    lv_obj_set_height(ui_label1number7, 50);
    lv_obj_set_x(ui_label1number7, 3);
    lv_obj_set_y(ui_label1number7, -12);
    lv_obj_set_align(ui_label1number7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number7, "鱼香肉丝17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number7, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number7 = lv_label_create(ui_infcontainernumber7);
    lv_obj_set_width(ui_label2number7, 129);
    lv_obj_set_height(ui_label2number7, 20);
    lv_obj_set_x(ui_label2number7, 3);
    lv_obj_set_y(ui_label2number7, 23);
    lv_obj_set_align(ui_label2number7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number7, "已购买");
    lv_obj_set_style_text_font(ui_label2number7, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber7 = lv_imgbtn_create(ui_infcontainernumber7);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber7, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber7, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber7, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber7, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber7, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber7, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber7, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber7, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber7, LV_ALIGN_CENTER);

    ui_number6 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number6);
    lv_obj_set_width(ui_number6, 200);
    lv_obj_set_height(ui_number6, 200);
    lv_obj_set_x(ui_number6, -716);
    lv_obj_set_y(ui_number6, -186);
    lv_obj_set_align(ui_number6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber6 = lv_img_create(ui_number6);
    lv_img_set_src(ui_Imagenumber6, &ui_img_1926326647);
    lv_obj_set_width(ui_Imagenumber6, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber6, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber6 = lv_obj_create(ui_number6);
    lv_obj_remove_style_all(ui_infcontainernumber6);
    lv_obj_set_width(ui_infcontainernumber6, 200);
    lv_obj_set_height(ui_infcontainernumber6, 80);
    lv_obj_set_align(ui_infcontainernumber6, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber6 = lv_imgbtn_create(ui_infcontainernumber6);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber6, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber6, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber6, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber6, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber6, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber6, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber6, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber6, 4);

    ui_label1number6 = lv_label_create(ui_infcontainernumber6);
    lv_obj_set_width(ui_label1number6, 129);
    lv_obj_set_height(ui_label1number6, 50);
    lv_obj_set_x(ui_label1number6, 3);
    lv_obj_set_y(ui_label1number6, -12);
    lv_obj_set_align(ui_label1number6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number6, "回锅肉29\n会员价20");
    lv_obj_set_style_text_font(ui_label1number6, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number6 = lv_label_create(ui_infcontainernumber6);
    lv_obj_set_width(ui_label2number6, 129);
    lv_obj_set_height(ui_label2number6, 20);
    lv_obj_set_x(ui_label2number6, 3);
    lv_obj_set_y(ui_label2number6, 23);
    lv_obj_set_align(ui_label2number6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number6, "已购买");
    lv_obj_set_style_text_font(ui_label2number6, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber6 = lv_imgbtn_create(ui_infcontainernumber6);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber6, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber6, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber6, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber6, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber6, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber6, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber6, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber6, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber6, LV_ALIGN_CENTER);

    ui_number5 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number5);
    lv_obj_set_width(ui_number5, 200);
    lv_obj_set_height(ui_number5, 200);
    lv_obj_set_x(ui_number5, -716);
    lv_obj_set_y(ui_number5, -186);
    lv_obj_set_align(ui_number5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber5 = lv_img_create(ui_number5);
    lv_img_set_src(ui_Imagenumber5, &ui_img_734771989);
    lv_obj_set_width(ui_Imagenumber5, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber5, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber5, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber5 = lv_obj_create(ui_number5);
    lv_obj_remove_style_all(ui_infcontainernumber5);
    lv_obj_set_width(ui_infcontainernumber5, 200);
    lv_obj_set_height(ui_infcontainernumber5, 80);
    lv_obj_set_align(ui_infcontainernumber5, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber5 = lv_imgbtn_create(ui_infcontainernumber5);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber5, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber5, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber5, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber5, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber5, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber5, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber5, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber5, 4);

    ui_label1number5 = lv_label_create(ui_infcontainernumber5);
    lv_obj_set_width(ui_label1number5, 129);
    lv_obj_set_height(ui_label1number5, 50);
    lv_obj_set_x(ui_label1number5, 3);
    lv_obj_set_y(ui_label1number5, -12);
    lv_obj_set_align(ui_label1number5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number5, "翡翠虾仁47\n会员价39");
    lv_obj_set_style_text_font(ui_label1number5, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number5 = lv_label_create(ui_infcontainernumber5);
    lv_obj_set_width(ui_label2number5, 129);
    lv_obj_set_height(ui_label2number5, 20);
    lv_obj_set_x(ui_label2number5, 3);
    lv_obj_set_y(ui_label2number5, 23);
    lv_obj_set_align(ui_label2number5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number5, "已购买");
    lv_obj_set_style_text_font(ui_label2number5, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber5 = lv_imgbtn_create(ui_infcontainernumber5);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber5, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber5, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber5, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber5, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber5, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber5, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber5, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber5, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber5, LV_ALIGN_CENTER);

    ui_number4 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number4);
    lv_obj_set_width(ui_number4, 200);
    lv_obj_set_height(ui_number4, 200);
    lv_obj_set_x(ui_number4, -716);
    lv_obj_set_y(ui_number4, -186);
    lv_obj_set_align(ui_number4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber4 = lv_img_create(ui_number4);
    lv_img_set_src(ui_Imagenumber4, &ui_img_1855500935);
    lv_obj_set_width(ui_Imagenumber4, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber4, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber4 = lv_obj_create(ui_number4);
    lv_obj_remove_style_all(ui_infcontainernumber4);
    lv_obj_set_width(ui_infcontainernumber4, 200);
    lv_obj_set_height(ui_infcontainernumber4, 80);
    lv_obj_set_align(ui_infcontainernumber4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber4 = lv_imgbtn_create(ui_infcontainernumber4);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber4, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber4, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber4, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber4, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber4, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber4, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber4, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber4, 4);

    ui_label5number4 = lv_label_create(ui_infcontainernumber4);
    lv_obj_set_width(ui_label5number4, 129);
    lv_obj_set_height(ui_label5number4, 50);
    lv_obj_set_x(ui_label5number4, 3);
    lv_obj_set_y(ui_label5number4, -12);
    lv_obj_set_align(ui_label5number4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label5number4, "宫保鸡丁17\n会员价15");
    lv_obj_set_style_text_font(ui_label5number4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1number4 = lv_label_create(ui_infcontainernumber4);
    lv_obj_set_width(ui_label1number4, 129);
    lv_obj_set_height(ui_label1number4, 20);
    lv_obj_set_x(ui_label1number4, 3);
    lv_obj_set_y(ui_label1number4, 23);
    lv_obj_set_align(ui_label1number4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number4, "已购买");
    lv_obj_set_style_text_font(ui_label1number4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonright3number4 = lv_imgbtn_create(ui_infcontainernumber4);
    lv_imgbtn_set_src(ui_ImgButtonright3number4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number4, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number4, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number4, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonright3number4, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonright3number4, 30);
    lv_obj_set_height(ui_ImgButtonright3number4, 40);
    lv_obj_set_x(ui_ImgButtonright3number4, 82);
    lv_obj_set_y(ui_ImgButtonright3number4, -16);
    lv_obj_set_align(ui_ImgButtonright3number4, LV_ALIGN_CENTER);

    ui_number3 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number3);
    lv_obj_set_width(ui_number3, 200);
    lv_obj_set_height(ui_number3, 200);
    lv_obj_set_x(ui_number3, -716);
    lv_obj_set_y(ui_number3, -186);
    lv_obj_set_align(ui_number3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber3 = lv_img_create(ui_number3);
    lv_img_set_src(ui_Imagenumber3, &ui_img_293691247);
    lv_obj_set_width(ui_Imagenumber3, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber3, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber3 = lv_obj_create(ui_number3);
    lv_obj_remove_style_all(ui_infcontainernumber3);
    lv_obj_set_width(ui_infcontainernumber3, 200);
    lv_obj_set_height(ui_infcontainernumber3, 80);
    lv_obj_set_align(ui_infcontainernumber3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber3 = lv_imgbtn_create(ui_infcontainernumber3);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber3, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber3, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber3, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber3, 4);

    ui_labelnumber3 = lv_label_create(ui_infcontainernumber3);
    lv_obj_set_width(ui_labelnumber3, 129);
    lv_obj_set_height(ui_labelnumber3, 50);
    lv_obj_set_x(ui_labelnumber3, 3);
    lv_obj_set_y(ui_labelnumber3, -12);
    lv_obj_set_align(ui_labelnumber3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelnumber3, "秘制红烧肉46\n会员价35");
    lv_obj_set_style_text_font(ui_labelnumber3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1number3 = lv_label_create(ui_infcontainernumber3);
    lv_obj_set_width(ui_label1number3, 129);
    lv_obj_set_height(ui_label1number3, 20);
    lv_obj_set_x(ui_label1number3, 3);
    lv_obj_set_y(ui_label1number3, 23);
    lv_obj_set_align(ui_label1number3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number3, "已购买");
    lv_obj_set_style_text_font(ui_label1number3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber3 = lv_imgbtn_create(ui_infcontainernumber3);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber3, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber3, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber3, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber3, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber3, LV_ALIGN_CENTER);

    ui_number2 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number2);
    lv_obj_set_width(ui_number2, 200);
    lv_obj_set_height(ui_number2, 200);
    lv_obj_set_x(ui_number2, -716);
    lv_obj_set_y(ui_number2, -186);
    lv_obj_set_align(ui_number2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber2 = lv_img_create(ui_number2);
    lv_img_set_src(ui_Imagenumber2, &ui_img_1341173067);
    lv_obj_set_width(ui_Imagenumber2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber2, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber2 = lv_obj_create(ui_number2);
    lv_obj_remove_style_all(ui_infcontainernumber2);
    lv_obj_set_width(ui_infcontainernumber2, 200);
    lv_obj_set_height(ui_infcontainernumber2, 80);
    lv_obj_set_align(ui_infcontainernumber2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber2 = lv_imgbtn_create(ui_infcontainernumber2);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber2, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber2, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber2, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber2, 4);

    ui_label1number2 = lv_label_create(ui_infcontainernumber2);
    lv_obj_set_width(ui_label1number2, 129);
    lv_obj_set_height(ui_label1number2, 50);
    lv_obj_set_x(ui_label1number2, 3);
    lv_obj_set_y(ui_label1number2, -12);
    lv_obj_set_align(ui_label1number2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number2, "新红烧肉32\n会员价25");
    lv_obj_set_style_text_font(ui_label1number2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number2 = lv_label_create(ui_infcontainernumber2);
    lv_obj_set_width(ui_label2number2, 129);
    lv_obj_set_height(ui_label2number2, 20);
    lv_obj_set_x(ui_label2number2, 3);
    lv_obj_set_y(ui_label2number2, 23);
    lv_obj_set_align(ui_label2number2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number2, "已购买");
    lv_obj_set_style_text_font(ui_label2number2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber2 = lv_imgbtn_create(ui_infcontainernumber2);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber2, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber2, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber2, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber2, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber2, LV_ALIGN_CENTER);

    ui_number1 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_number1);
    lv_obj_set_width(ui_number1, 200);
    lv_obj_set_height(ui_number1, 200);
    lv_obj_set_x(ui_number1, -716);
    lv_obj_set_y(ui_number1, -186);
    lv_obj_set_align(ui_number1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagenumber1 = lv_img_create(ui_number1);
    lv_img_set_src(ui_Imagenumber1, &ui_img_2092529074);
    lv_obj_set_width(ui_Imagenumber1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Imagenumber1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Imagenumber1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imagenumber1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenumber1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infcontainernumber1 = lv_obj_create(ui_number1);
    lv_obj_remove_style_all(ui_infcontainernumber1);
    lv_obj_set_width(ui_infcontainernumber1, 200);
    lv_obj_set_height(ui_infcontainernumber1, 80);
    lv_obj_set_align(ui_infcontainernumber1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_infcontainernumber1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonleftnumber1 = lv_imgbtn_create(ui_infcontainernumber1);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonleftnumber1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonleftnumber1, 30);
    lv_obj_set_height(ui_ImgButtonleftnumber1, 40);
    lv_obj_set_x(ui_ImgButtonleftnumber1, 2);
    lv_obj_set_y(ui_ImgButtonleftnumber1, 4);

    ui_label1number1 = lv_label_create(ui_infcontainernumber1);
    lv_obj_set_width(ui_label1number1, 129);
    lv_obj_set_height(ui_label1number1, 50);
    lv_obj_set_x(ui_label1number1, 3);
    lv_obj_set_y(ui_label1number1, -12);
    lv_obj_set_align(ui_label1number1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1number1, "红烧鲈鱼17\n会员价15");
    lv_obj_set_style_text_font(ui_label1number1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2number1 = lv_label_create(ui_infcontainernumber1);
    lv_obj_set_width(ui_label2number1, 129);
    lv_obj_set_height(ui_label2number1, 20);
    lv_obj_set_x(ui_label2number1, 3);
    lv_obj_set_y(ui_label2number1, 23);
    lv_obj_set_align(ui_label2number1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2number1, "已购买");
    lv_obj_set_style_text_font(ui_label2number1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonrightnumber1 = lv_imgbtn_create(ui_infcontainernumber1);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButtonrightnumber1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButtonrightnumber1, 30);
    lv_obj_set_height(ui_ImgButtonrightnumber1, 40);
    lv_obj_set_x(ui_ImgButtonrightnumber1, 82);
    lv_obj_set_y(ui_ImgButtonrightnumber1, -16);
    lv_obj_set_align(ui_ImgButtonrightnumber1, LV_ALIGN_CENTER);

    ui_ImgButton1 = lv_imgbtn_create(ui_order1);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButton1, 50);
    lv_obj_set_height(ui_ImgButton1, 30);
    lv_obj_set_x(ui_ImgButton1, -483);
    lv_obj_set_y(ui_ImgButton1, 281);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_ImgButton2 = lv_imgbtn_create(ui_order1);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton2, 64);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton2, -82);
    lv_obj_set_y(ui_ImgButton2, 245);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_ImgButton3 = lv_imgbtn_create(ui_order1);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton3, 64);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton3, 140);
    lv_obj_set_y(ui_ImgButton3, 245);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_Buttonconfirm1 = lv_btn_create(ui_order1);
    lv_obj_set_width(ui_Buttonconfirm1, 100);
    lv_obj_set_height(ui_Buttonconfirm1, 50);
    lv_obj_set_x(ui_Buttonconfirm1, 18);
    lv_obj_set_y(ui_Buttonconfirm1, 242);
    lv_obj_set_align(ui_Buttonconfirm1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonconfirm1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonconfirm1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelconfirm1 = lv_label_create(ui_Buttonconfirm1);
    lv_obj_set_width(ui_Labelconfirm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelconfirm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelconfirm1, -1);
    lv_obj_set_y(ui_Labelconfirm1, 4);
    lv_obj_set_align(ui_Labelconfirm1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelconfirm1, "结账");
    lv_obj_set_style_text_font(ui_Labelconfirm1, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);

}
