// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#include "../ui.h"

void ui_orderscreen1_screen_init(void)
{
    ui_orderscreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_orderscreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_orderscreen1, &ui_img_1485140228, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_orderscreen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 924);
    lv_obj_set_height(ui_Container2, 405);
    lv_obj_set_x(ui_Container2, -5);
    lv_obj_set_y(ui_Container2, -71);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number8container = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_number8container);
    lv_obj_set_width(ui_number8container, 200);
    lv_obj_set_height(ui_number8container, 200);
    lv_obj_set_x(ui_number8container, -716);
    lv_obj_set_y(ui_number8container, -186);
    lv_obj_set_align(ui_number8container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number8container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number8Image = lv_img_create(ui_number8container);
    lv_img_set_src(ui_number8Image, &ui_img_1429700948);
    lv_obj_set_width(ui_number8Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number8Image, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number8Image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number8Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number8Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number8infcontainer = lv_obj_create(ui_number8container);
    lv_obj_remove_style_all(ui_number8infcontainer);
    lv_obj_set_width(ui_number8infcontainer, 200);
    lv_obj_set_height(ui_number8infcontainer, 80);
    lv_obj_set_align(ui_number8infcontainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number8infcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number8ImgButtonleft = lv_imgbtn_create(ui_number8infcontainer);
    lv_imgbtn_set_src(ui_number8ImgButtonleft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number8ImgButtonleft, 30);
    lv_obj_set_height(ui_number8ImgButtonleft, 40);
    lv_obj_set_x(ui_number8ImgButtonleft, 2);
    lv_obj_set_y(ui_number8ImgButtonleft, 4);

    ui_number8label1 = lv_label_create(ui_number8infcontainer);
    lv_obj_set_width(ui_number8label1, 129);
    lv_obj_set_height(ui_number8label1, 50);
    lv_obj_set_x(ui_number8label1, 3);
    lv_obj_set_y(ui_number8label1, -12);
    lv_obj_set_align(ui_number8label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number8label1, "番茄炒蛋17\n会员价15");
    lv_obj_set_style_text_font(ui_number8label1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number8label2 = lv_label_create(ui_number8infcontainer);
    lv_obj_set_width(ui_number8label2, 129);
    lv_obj_set_height(ui_number8label2, 20);
    lv_obj_set_x(ui_number8label2, 3);
    lv_obj_set_y(ui_number8label2, 23);
    lv_obj_set_align(ui_number8label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number8label2, "已购买");
    lv_obj_set_style_text_font(ui_number8label2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number8ImgButtonright = lv_imgbtn_create(ui_number8infcontainer);
    lv_imgbtn_set_src(ui_number8ImgButtonright, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number8ImgButtonright, 30);
    lv_obj_set_height(ui_number8ImgButtonright, 40);
    lv_obj_set_x(ui_number8ImgButtonright, 82);
    lv_obj_set_y(ui_number8ImgButtonright, -16);
    lv_obj_set_align(ui_number8ImgButtonright, LV_ALIGN_CENTER);

    ui_number7container = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_number7container);
    lv_obj_set_width(ui_number7container, 200);
    lv_obj_set_height(ui_number7container, 200);
    lv_obj_set_x(ui_number7container, -716);
    lv_obj_set_y(ui_number7container, -186);
    lv_obj_set_align(ui_number7container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number7container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number7Image = lv_img_create(ui_number7container);
    lv_img_set_src(ui_number7Image, &ui_img_682017832);
    lv_obj_set_width(ui_number7Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number7Image, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number7Image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number7Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number7Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number7infcontainer = lv_obj_create(ui_number7container);
    lv_obj_remove_style_all(ui_number7infcontainer);
    lv_obj_set_width(ui_number7infcontainer, 200);
    lv_obj_set_height(ui_number7infcontainer, 80);
    lv_obj_set_align(ui_number7infcontainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number7infcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number7ImgButtonleft = lv_imgbtn_create(ui_number7infcontainer);
    lv_imgbtn_set_src(ui_number7ImgButtonleft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number7ImgButtonleft, 30);
    lv_obj_set_height(ui_number7ImgButtonleft, 40);
    lv_obj_set_x(ui_number7ImgButtonleft, 2);
    lv_obj_set_y(ui_number7ImgButtonleft, 4);

    ui_number7label1 = lv_label_create(ui_number7infcontainer);
    lv_obj_set_width(ui_number7label1, 129);
    lv_obj_set_height(ui_number7label1, 50);
    lv_obj_set_x(ui_number7label1, 3);
    lv_obj_set_y(ui_number7label1, -12);
    lv_obj_set_align(ui_number7label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number7label1, "鱼香肉丝17\n会员价15");
    lv_obj_set_style_text_font(ui_number7label1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number7label2 = lv_label_create(ui_number7infcontainer);
    lv_obj_set_width(ui_number7label2, 129);
    lv_obj_set_height(ui_number7label2, 20);
    lv_obj_set_x(ui_number7label2, 3);
    lv_obj_set_y(ui_number7label2, 23);
    lv_obj_set_align(ui_number7label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number7label2, "已购买");
    lv_obj_set_style_text_font(ui_number7label2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number7ImgButtonright = lv_imgbtn_create(ui_number7infcontainer);
    lv_imgbtn_set_src(ui_number7ImgButtonright, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number7ImgButtonright, 30);
    lv_obj_set_height(ui_number7ImgButtonright, 40);
    lv_obj_set_x(ui_number7ImgButtonright, 82);
    lv_obj_set_y(ui_number7ImgButtonright, -16);
    lv_obj_set_align(ui_number7ImgButtonright, LV_ALIGN_CENTER);

    ui_number6container = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_number6container);
    lv_obj_set_width(ui_number6container, 200);
    lv_obj_set_height(ui_number6container, 200);
    lv_obj_set_x(ui_number6container, -716);
    lv_obj_set_y(ui_number6container, -186);
    lv_obj_set_align(ui_number6container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number6container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number6Image = lv_img_create(ui_number6container);
    lv_img_set_src(ui_number6Image, &ui_img_1926326647);
    lv_obj_set_width(ui_number6Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number6Image, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number6Image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number6Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number6Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number6infcontainer = lv_obj_create(ui_number6container);
    lv_obj_remove_style_all(ui_number6infcontainer);
    lv_obj_set_width(ui_number6infcontainer, 200);
    lv_obj_set_height(ui_number6infcontainer, 80);
    lv_obj_set_align(ui_number6infcontainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number6infcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number6ImgButtonleft = lv_imgbtn_create(ui_number6infcontainer);
    lv_imgbtn_set_src(ui_number6ImgButtonleft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number6ImgButtonleft, 30);
    lv_obj_set_height(ui_number6ImgButtonleft, 40);
    lv_obj_set_x(ui_number6ImgButtonleft, 2);
    lv_obj_set_y(ui_number6ImgButtonleft, 4);

    ui_number6label1 = lv_label_create(ui_number6infcontainer);
    lv_obj_set_width(ui_number6label1, 129);
    lv_obj_set_height(ui_number6label1, 50);
    lv_obj_set_x(ui_number6label1, 3);
    lv_obj_set_y(ui_number6label1, -12);
    lv_obj_set_align(ui_number6label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number6label1, "回锅肉29\n会员价20");
    lv_obj_set_style_text_font(ui_number6label1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number6label2 = lv_label_create(ui_number6infcontainer);
    lv_obj_set_width(ui_number6label2, 129);
    lv_obj_set_height(ui_number6label2, 20);
    lv_obj_set_x(ui_number6label2, 3);
    lv_obj_set_y(ui_number6label2, 23);
    lv_obj_set_align(ui_number6label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number6label2, "已购买");
    lv_obj_set_style_text_font(ui_number6label2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number6ImgButtonright = lv_imgbtn_create(ui_number6infcontainer);
    lv_imgbtn_set_src(ui_number6ImgButtonright, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number6ImgButtonright, 30);
    lv_obj_set_height(ui_number6ImgButtonright, 40);
    lv_obj_set_x(ui_number6ImgButtonright, 82);
    lv_obj_set_y(ui_number6ImgButtonright, -16);
    lv_obj_set_align(ui_number6ImgButtonright, LV_ALIGN_CENTER);

    ui_number5container = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_number5container);
    lv_obj_set_width(ui_number5container, 200);
    lv_obj_set_height(ui_number5container, 200);
    lv_obj_set_x(ui_number5container, -716);
    lv_obj_set_y(ui_number5container, -186);
    lv_obj_set_align(ui_number5container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number5container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number5Image = lv_img_create(ui_number5container);
    lv_img_set_src(ui_number5Image, &ui_img_1341173067);
    lv_obj_set_width(ui_number5Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number5Image, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number5Image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number5Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number5Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number5infcontainer = lv_obj_create(ui_number5container);
    lv_obj_remove_style_all(ui_number5infcontainer);
    lv_obj_set_width(ui_number5infcontainer, 200);
    lv_obj_set_height(ui_number5infcontainer, 80);
    lv_obj_set_align(ui_number5infcontainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number5infcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number5ImgButtonleft = lv_imgbtn_create(ui_number5infcontainer);
    lv_imgbtn_set_src(ui_number5ImgButtonleft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number5ImgButtonleft, 30);
    lv_obj_set_height(ui_number5ImgButtonleft, 40);
    lv_obj_set_x(ui_number5ImgButtonleft, 2);
    lv_obj_set_y(ui_number5ImgButtonleft, 4);

    ui_number5label1 = lv_label_create(ui_number5infcontainer);
    lv_obj_set_width(ui_number5label1, 129);
    lv_obj_set_height(ui_number5label1, 50);
    lv_obj_set_x(ui_number5label1, 3);
    lv_obj_set_y(ui_number5label1, -12);
    lv_obj_set_align(ui_number5label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number5label1, "新红烧肉32\n会员价25");
    lv_obj_set_style_text_font(ui_number5label1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number5label2 = lv_label_create(ui_number5infcontainer);
    lv_obj_set_width(ui_number5label2, 129);
    lv_obj_set_height(ui_number5label2, 20);
    lv_obj_set_x(ui_number5label2, 3);
    lv_obj_set_y(ui_number5label2, 23);
    lv_obj_set_align(ui_number5label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number5label2, "已购买");
    lv_obj_set_style_text_font(ui_number5label2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number5ImgButtonright = lv_imgbtn_create(ui_number5infcontainer);
    lv_imgbtn_set_src(ui_number5ImgButtonright, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number5ImgButtonright, 30);
    lv_obj_set_height(ui_number5ImgButtonright, 40);
    lv_obj_set_x(ui_number5ImgButtonright, 82);
    lv_obj_set_y(ui_number5ImgButtonright, -16);
    lv_obj_set_align(ui_number5ImgButtonright, LV_ALIGN_CENTER);

    ui_number4container = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_number4container);
    lv_obj_set_width(ui_number4container, 200);
    lv_obj_set_height(ui_number4container, 200);
    lv_obj_set_x(ui_number4container, -716);
    lv_obj_set_y(ui_number4container, -186);
    lv_obj_set_align(ui_number4container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number4container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number4Image = lv_img_create(ui_number4container);
    lv_img_set_src(ui_number4Image, &ui_img_293691247);
    lv_obj_set_width(ui_number4Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number4Image, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number4Image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number4Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number4Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number4infcontainer = lv_obj_create(ui_number4container);
    lv_obj_remove_style_all(ui_number4infcontainer);
    lv_obj_set_width(ui_number4infcontainer, 200);
    lv_obj_set_height(ui_number4infcontainer, 80);
    lv_obj_set_align(ui_number4infcontainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number4infcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number4ImgButtonleft = lv_imgbtn_create(ui_number4infcontainer);
    lv_imgbtn_set_src(ui_number4ImgButtonleft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number4ImgButtonleft, 30);
    lv_obj_set_height(ui_number4ImgButtonleft, 40);
    lv_obj_set_x(ui_number4ImgButtonleft, 2);
    lv_obj_set_y(ui_number4ImgButtonleft, 4);

    ui_number4label1 = lv_label_create(ui_number4infcontainer);
    lv_obj_set_width(ui_number4label1, 129);
    lv_obj_set_height(ui_number4label1, 50);
    lv_obj_set_x(ui_number4label1, 3);
    lv_obj_set_y(ui_number4label1, -12);
    lv_obj_set_align(ui_number4label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number4label1, "秘制红烧肉46\n会员价35");
    lv_obj_set_style_text_font(ui_number4label1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number4label2 = lv_label_create(ui_number4infcontainer);
    lv_obj_set_width(ui_number4label2, 129);
    lv_obj_set_height(ui_number4label2, 20);
    lv_obj_set_x(ui_number4label2, 3);
    lv_obj_set_y(ui_number4label2, 23);
    lv_obj_set_align(ui_number4label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number4label2, "已购买");
    lv_obj_set_style_text_font(ui_number4label2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number4ImgButtonright = lv_imgbtn_create(ui_number4infcontainer);
    lv_imgbtn_set_src(ui_number4ImgButtonright, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number4ImgButtonright, 30);
    lv_obj_set_height(ui_number4ImgButtonright, 40);
    lv_obj_set_x(ui_number4ImgButtonright, 82);
    lv_obj_set_y(ui_number4ImgButtonright, -16);
    lv_obj_set_align(ui_number4ImgButtonright, LV_ALIGN_CENTER);

    ui_number3container = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_number3container);
    lv_obj_set_width(ui_number3container, 200);
    lv_obj_set_height(ui_number3container, 200);
    lv_obj_set_x(ui_number3container, -716);
    lv_obj_set_y(ui_number3container, -186);
    lv_obj_set_align(ui_number3container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number3container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number3Image = lv_img_create(ui_number3container);
    lv_img_set_src(ui_number3Image, &ui_img_734771989);
    lv_obj_set_width(ui_number3Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number3Image, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number3Image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number3Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number3Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number3infcontainer = lv_obj_create(ui_number3container);
    lv_obj_remove_style_all(ui_number3infcontainer);
    lv_obj_set_width(ui_number3infcontainer, 200);
    lv_obj_set_height(ui_number3infcontainer, 80);
    lv_obj_set_align(ui_number3infcontainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number3infcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number3ImgButtonleft = lv_imgbtn_create(ui_number3infcontainer);
    lv_imgbtn_set_src(ui_number3ImgButtonleft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number3ImgButtonleft, 30);
    lv_obj_set_height(ui_number3ImgButtonleft, 40);
    lv_obj_set_x(ui_number3ImgButtonleft, 2);
    lv_obj_set_y(ui_number3ImgButtonleft, 4);

    ui_number3label1 = lv_label_create(ui_number3infcontainer);
    lv_obj_set_width(ui_number3label1, 129);
    lv_obj_set_height(ui_number3label1, 50);
    lv_obj_set_x(ui_number3label1, 3);
    lv_obj_set_y(ui_number3label1, -12);
    lv_obj_set_align(ui_number3label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number3label1, "翡翠虾仁47\n会员价39");
    lv_obj_set_style_text_font(ui_number3label1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number3label2 = lv_label_create(ui_number3infcontainer);
    lv_obj_set_width(ui_number3label2, 129);
    lv_obj_set_height(ui_number3label2, 20);
    lv_obj_set_x(ui_number3label2, 3);
    lv_obj_set_y(ui_number3label2, 23);
    lv_obj_set_align(ui_number3label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number3label2, "已购买");
    lv_obj_set_style_text_font(ui_number3label2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number3ImgButtonright = lv_imgbtn_create(ui_number3infcontainer);
    lv_imgbtn_set_src(ui_number3ImgButtonright, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number3ImgButtonright, 30);
    lv_obj_set_height(ui_number3ImgButtonright, 40);
    lv_obj_set_x(ui_number3ImgButtonright, 82);
    lv_obj_set_y(ui_number3ImgButtonright, -16);
    lv_obj_set_align(ui_number3ImgButtonright, LV_ALIGN_CENTER);

    ui_number2container = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_number2container);
    lv_obj_set_width(ui_number2container, 200);
    lv_obj_set_height(ui_number2container, 200);
    lv_obj_set_x(ui_number2container, -716);
    lv_obj_set_y(ui_number2container, -186);
    lv_obj_set_align(ui_number2container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number2container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number2Image = lv_img_create(ui_number2container);
    lv_img_set_src(ui_number2Image, &ui_img_1855500935);
    lv_obj_set_width(ui_number2Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number2Image, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number2Image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number2Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number2Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number2infcontainer = lv_obj_create(ui_number2container);
    lv_obj_remove_style_all(ui_number2infcontainer);
    lv_obj_set_width(ui_number2infcontainer, 200);
    lv_obj_set_height(ui_number2infcontainer, 80);
    lv_obj_set_align(ui_number2infcontainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number2infcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number2ImgButtonleft = lv_imgbtn_create(ui_number2infcontainer);
    lv_imgbtn_set_src(ui_number2ImgButtonleft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number2ImgButtonleft, 30);
    lv_obj_set_height(ui_number2ImgButtonleft, 40);
    lv_obj_set_x(ui_number2ImgButtonleft, 2);
    lv_obj_set_y(ui_number2ImgButtonleft, 4);

    ui_number2label1 = lv_label_create(ui_number2infcontainer);
    lv_obj_set_width(ui_number2label1, 129);
    lv_obj_set_height(ui_number2label1, 50);
    lv_obj_set_x(ui_number2label1, 3);
    lv_obj_set_y(ui_number2label1, -12);
    lv_obj_set_align(ui_number2label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number2label1, "宫保鸡丁17\n会员价15");
    lv_obj_set_style_text_font(ui_number2label1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number2label2 = lv_label_create(ui_number2infcontainer);
    lv_obj_set_width(ui_number2label2, 129);
    lv_obj_set_height(ui_number2label2, 20);
    lv_obj_set_x(ui_number2label2, 3);
    lv_obj_set_y(ui_number2label2, 23);
    lv_obj_set_align(ui_number2label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number2label2, "已购买");
    lv_obj_set_style_text_font(ui_number2label2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number2ImgButtonright = lv_imgbtn_create(ui_number2infcontainer);
    lv_imgbtn_set_src(ui_number2ImgButtonright, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number2ImgButtonright, 30);
    lv_obj_set_height(ui_number2ImgButtonright, 40);
    lv_obj_set_x(ui_number2ImgButtonright, 82);
    lv_obj_set_y(ui_number2ImgButtonright, -16);
    lv_obj_set_align(ui_number2ImgButtonright, LV_ALIGN_CENTER);

    ui_number1container = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_number1container);
    lv_obj_set_width(ui_number1container, 200);
    lv_obj_set_height(ui_number1container, 200);
    lv_obj_set_x(ui_number1container, -716);
    lv_obj_set_y(ui_number1container, -186);
    lv_obj_set_align(ui_number1container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number1container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number1Image = lv_img_create(ui_number1container);
    lv_img_set_src(ui_number1Image, &ui_img_2092529074);
    lv_obj_set_width(ui_number1Image, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number1Image, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number1Image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number1Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number1Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number1infcontainer = lv_obj_create(ui_number1container);
    lv_obj_remove_style_all(ui_number1infcontainer);
    lv_obj_set_width(ui_number1infcontainer, 200);
    lv_obj_set_height(ui_number1infcontainer, 80);
    lv_obj_set_align(ui_number1infcontainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number1infcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number1ImgButtonleft = lv_imgbtn_create(ui_number1infcontainer);
    lv_imgbtn_set_src(ui_number1ImgButtonleft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number1ImgButtonleft, 30);
    lv_obj_set_height(ui_number1ImgButtonleft, 40);
    lv_obj_set_x(ui_number1ImgButtonleft, 2);
    lv_obj_set_y(ui_number1ImgButtonleft, 4);

    ui_number1label1 = lv_label_create(ui_number1infcontainer);
    lv_obj_set_width(ui_number1label1, 129);
    lv_obj_set_height(ui_number1label1, 50);
    lv_obj_set_x(ui_number1label1, 3);
    lv_obj_set_y(ui_number1label1, -12);
    lv_obj_set_align(ui_number1label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number1label1, "红烧鲈鱼17\n会员价15");
    lv_obj_set_style_text_font(ui_number1label1, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number1label2 = lv_label_create(ui_number1infcontainer);
    lv_obj_set_width(ui_number1label2, 129);
    lv_obj_set_height(ui_number1label2, 20);
    lv_obj_set_x(ui_number1label2, 3);
    lv_obj_set_y(ui_number1label2, 23);
    lv_obj_set_align(ui_number1label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number1label2, "已购买");
    lv_obj_set_style_text_font(ui_number1label2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number1ImgButtonright = lv_imgbtn_create(ui_number1infcontainer);
    lv_imgbtn_set_src(ui_number1ImgButtonright, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number1ImgButtonright, 30);
    lv_obj_set_height(ui_number1ImgButtonright, 40);
    lv_obj_set_x(ui_number1ImgButtonright, 82);
    lv_obj_set_y(ui_number1ImgButtonright, -16);
    lv_obj_set_align(ui_number1ImgButtonright, LV_ALIGN_CENTER);

    ui_Container4 = lv_obj_create(ui_orderscreen1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 910);
    lv_obj_set_height(ui_Container4, 74);
    lv_obj_set_x(ui_Container4, 6);
    lv_obj_set_y(ui_Container4, 254);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lastpageButton1 = lv_imgbtn_create(ui_Container4);
    lv_imgbtn_set_src(ui_lastpageButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_lastpageButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_lastpageButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButton1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_lastpageButton1, 60);
    lv_obj_set_height(ui_lastpageButton1, 60);
    lv_obj_set_x(ui_lastpageButton1, -100);
    lv_obj_set_y(ui_lastpageButton1, -8);
    lv_obj_set_align(ui_lastpageButton1, LV_ALIGN_CENTER);

    ui_nextpageButton2 = lv_imgbtn_create(ui_Container4);
    lv_imgbtn_set_src(ui_nextpageButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_nextpageButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_nextpageButton2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButton2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButton2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButton2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_nextpageButton2, 60);
    lv_obj_set_height(ui_nextpageButton2, 60);
    lv_obj_set_x(ui_nextpageButton2, -316);
    lv_obj_set_y(ui_nextpageButton2, 0);
    lv_obj_set_align(ui_nextpageButton2, LV_ALIGN_TOP_RIGHT);

    ui_backButton1 = lv_imgbtn_create(ui_Container4);
    lv_imgbtn_set_src(ui_backButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_backButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_backButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_backButton1, 50);
    lv_obj_set_height(ui_backButton1, 32);
    lv_obj_set_x(ui_backButton1, 17);
    lv_obj_set_y(ui_backButton1, 39);

    ui_confirmButton1 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_confirmButton1, 100);
    lv_obj_set_height(ui_confirmButton1, 50);
    lv_obj_set_align(ui_confirmButton1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_confirmButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_confirmButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_confirmButton1, lv_color_hex(0x99CCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confirmButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_confirmButton1, lv_color_hex(0x6699FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_confirmButton1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmLabel1 = lv_label_create(ui_confirmButton1);
    lv_obj_set_width(ui_confirmLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confirmLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_confirmLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confirmLabel1, "结账");
    lv_obj_set_style_text_color(ui_confirmLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confirmLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confirmLabel1, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_nextpageButton2, ui_event_nextpageButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton1, ui_event_backButton1, LV_EVENT_ALL, NULL);

}
