// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test1

#include "../ui.h"

void ui_orderscreen2_screen_init(void)
{
    ui_orderscreen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_orderscreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_orderscreen2, &ui_img_1485140228, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_orderscreen2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 924);
    lv_obj_set_height(ui_Container3, 405);
    lv_obj_set_x(ui_Container3, -5);
    lv_obj_set_y(ui_Container3, -71);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number8container1 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_number8container1);
    lv_obj_set_width(ui_number8container1, 200);
    lv_obj_set_height(ui_number8container1, 200);
    lv_obj_set_x(ui_number8container1, -716);
    lv_obj_set_y(ui_number8container1, -186);
    lv_obj_set_align(ui_number8container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number8container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number8Image1 = lv_img_create(ui_number8container1);
    lv_img_set_src(ui_number8Image1, &ui_img_112040420);
    lv_obj_set_width(ui_number8Image1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number8Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number8Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number8Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number8Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number8infcontainer1 = lv_obj_create(ui_number8container1);
    lv_obj_remove_style_all(ui_number8infcontainer1);
    lv_obj_set_width(ui_number8infcontainer1, 200);
    lv_obj_set_height(ui_number8infcontainer1, 80);
    lv_obj_set_align(ui_number8infcontainer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number8infcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number8ImgButtonleft1 = lv_imgbtn_create(ui_number8infcontainer1);
    lv_imgbtn_set_src(ui_number8ImgButtonleft1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number8ImgButtonleft1, 30);
    lv_obj_set_height(ui_number8ImgButtonleft1, 40);
    lv_obj_set_x(ui_number8ImgButtonleft1, 2);
    lv_obj_set_y(ui_number8ImgButtonleft1, 4);

    ui_number8label3 = lv_label_create(ui_number8infcontainer1);
    lv_obj_set_width(ui_number8label3, 129);
    lv_obj_set_height(ui_number8label3, 50);
    lv_obj_set_x(ui_number8label3, 3);
    lv_obj_set_y(ui_number8label3, -12);
    lv_obj_set_align(ui_number8label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number8label3, "土豆牛肉17\n会员价15");
    lv_obj_set_style_text_font(ui_number8label3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number8label4 = lv_label_create(ui_number8infcontainer1);
    lv_obj_set_width(ui_number8label4, 129);
    lv_obj_set_height(ui_number8label4, 20);
    lv_obj_set_x(ui_number8label4, 3);
    lv_obj_set_y(ui_number8label4, 23);
    lv_obj_set_align(ui_number8label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number8label4, "已购买");
    lv_obj_set_style_text_font(ui_number8label4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number8ImgButtonright1 = lv_imgbtn_create(ui_number8infcontainer1);
    lv_imgbtn_set_src(ui_number8ImgButtonright1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number8ImgButtonright1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number8ImgButtonright1, 30);
    lv_obj_set_height(ui_number8ImgButtonright1, 40);
    lv_obj_set_x(ui_number8ImgButtonright1, 82);
    lv_obj_set_y(ui_number8ImgButtonright1, -16);
    lv_obj_set_align(ui_number8ImgButtonright1, LV_ALIGN_CENTER);

    ui_number7container1 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_number7container1);
    lv_obj_set_width(ui_number7container1, 200);
    lv_obj_set_height(ui_number7container1, 200);
    lv_obj_set_x(ui_number7container1, -716);
    lv_obj_set_y(ui_number7container1, -186);
    lv_obj_set_align(ui_number7container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number7container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number7Image1 = lv_img_create(ui_number7container1);
    lv_img_set_src(ui_number7Image1, &ui_img_403749227);
    lv_obj_set_width(ui_number7Image1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number7Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number7Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number7Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number7Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number7infcontainer1 = lv_obj_create(ui_number7container1);
    lv_obj_remove_style_all(ui_number7infcontainer1);
    lv_obj_set_width(ui_number7infcontainer1, 200);
    lv_obj_set_height(ui_number7infcontainer1, 80);
    lv_obj_set_align(ui_number7infcontainer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number7infcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number7ImgButtonleft1 = lv_imgbtn_create(ui_number7infcontainer1);
    lv_imgbtn_set_src(ui_number7ImgButtonleft1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number7ImgButtonleft1, 30);
    lv_obj_set_height(ui_number7ImgButtonleft1, 40);
    lv_obj_set_x(ui_number7ImgButtonleft1, 2);
    lv_obj_set_y(ui_number7ImgButtonleft1, 4);

    ui_number7label3 = lv_label_create(ui_number7infcontainer1);
    lv_obj_set_width(ui_number7label3, 129);
    lv_obj_set_height(ui_number7label3, 50);
    lv_obj_set_x(ui_number7label3, 3);
    lv_obj_set_y(ui_number7label3, -12);
    lv_obj_set_align(ui_number7label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number7label3, "紫苏田螺17\n会员价15");
    lv_obj_set_style_text_font(ui_number7label3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number7label4 = lv_label_create(ui_number7infcontainer1);
    lv_obj_set_width(ui_number7label4, 129);
    lv_obj_set_height(ui_number7label4, 20);
    lv_obj_set_x(ui_number7label4, 3);
    lv_obj_set_y(ui_number7label4, 23);
    lv_obj_set_align(ui_number7label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number7label4, "已购买");
    lv_obj_set_style_text_font(ui_number7label4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number7ImgButtonright1 = lv_imgbtn_create(ui_number7infcontainer1);
    lv_imgbtn_set_src(ui_number7ImgButtonright1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number7ImgButtonright1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number7ImgButtonright1, 30);
    lv_obj_set_height(ui_number7ImgButtonright1, 40);
    lv_obj_set_x(ui_number7ImgButtonright1, 82);
    lv_obj_set_y(ui_number7ImgButtonright1, -16);
    lv_obj_set_align(ui_number7ImgButtonright1, LV_ALIGN_CENTER);

    ui_number6container1 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_number6container1);
    lv_obj_set_width(ui_number6container1, 200);
    lv_obj_set_height(ui_number6container1, 200);
    lv_obj_set_x(ui_number6container1, -716);
    lv_obj_set_y(ui_number6container1, -186);
    lv_obj_set_align(ui_number6container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number6container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number6Image1 = lv_img_create(ui_number6container1);
    lv_img_set_src(ui_number6Image1, &ui_img_1181513690);
    lv_obj_set_width(ui_number6Image1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number6Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number6Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number6Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number6Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number6infcontainer1 = lv_obj_create(ui_number6container1);
    lv_obj_remove_style_all(ui_number6infcontainer1);
    lv_obj_set_width(ui_number6infcontainer1, 200);
    lv_obj_set_height(ui_number6infcontainer1, 80);
    lv_obj_set_align(ui_number6infcontainer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number6infcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number6ImgButtonleft1 = lv_imgbtn_create(ui_number6infcontainer1);
    lv_imgbtn_set_src(ui_number6ImgButtonleft1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number6ImgButtonleft1, 30);
    lv_obj_set_height(ui_number6ImgButtonleft1, 40);
    lv_obj_set_x(ui_number6ImgButtonleft1, 2);
    lv_obj_set_y(ui_number6ImgButtonleft1, 4);

    ui_number6label3 = lv_label_create(ui_number6infcontainer1);
    lv_obj_set_width(ui_number6label3, 129);
    lv_obj_set_height(ui_number6label3, 50);
    lv_obj_set_x(ui_number6label3, 3);
    lv_obj_set_y(ui_number6label3, -12);
    lv_obj_set_align(ui_number6label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number6label3, "红烧狮子头29\n会员价20");
    lv_obj_set_style_text_font(ui_number6label3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number6label4 = lv_label_create(ui_number6infcontainer1);
    lv_obj_set_width(ui_number6label4, 129);
    lv_obj_set_height(ui_number6label4, 20);
    lv_obj_set_x(ui_number6label4, 3);
    lv_obj_set_y(ui_number6label4, 23);
    lv_obj_set_align(ui_number6label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number6label4, "已购买");
    lv_obj_set_style_text_font(ui_number6label4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number6ImgButtonright1 = lv_imgbtn_create(ui_number6infcontainer1);
    lv_imgbtn_set_src(ui_number6ImgButtonright1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number6ImgButtonright1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number6ImgButtonright1, 30);
    lv_obj_set_height(ui_number6ImgButtonright1, 40);
    lv_obj_set_x(ui_number6ImgButtonright1, 82);
    lv_obj_set_y(ui_number6ImgButtonright1, -16);
    lv_obj_set_align(ui_number6ImgButtonright1, LV_ALIGN_CENTER);

    ui_number5container1 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_number5container1);
    lv_obj_set_width(ui_number5container1, 200);
    lv_obj_set_height(ui_number5container1, 200);
    lv_obj_set_x(ui_number5container1, -716);
    lv_obj_set_y(ui_number5container1, -186);
    lv_obj_set_align(ui_number5container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number5container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number5Image1 = lv_img_create(ui_number5container1);
    lv_img_set_src(ui_number5Image1, &ui_img_139154128);
    lv_obj_set_width(ui_number5Image1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number5Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number5Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number5Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number5Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number5infcontainer1 = lv_obj_create(ui_number5container1);
    lv_obj_remove_style_all(ui_number5infcontainer1);
    lv_obj_set_width(ui_number5infcontainer1, 200);
    lv_obj_set_height(ui_number5infcontainer1, 80);
    lv_obj_set_align(ui_number5infcontainer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number5infcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number5ImgButtonleft1 = lv_imgbtn_create(ui_number5infcontainer1);
    lv_imgbtn_set_src(ui_number5ImgButtonleft1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number5ImgButtonleft1, 30);
    lv_obj_set_height(ui_number5ImgButtonleft1, 40);
    lv_obj_set_x(ui_number5ImgButtonleft1, 2);
    lv_obj_set_y(ui_number5ImgButtonleft1, 4);

    ui_number5label3 = lv_label_create(ui_number5infcontainer1);
    lv_obj_set_width(ui_number5label3, 129);
    lv_obj_set_height(ui_number5label3, 50);
    lv_obj_set_x(ui_number5label3, 3);
    lv_obj_set_y(ui_number5label3, -12);
    lv_obj_set_align(ui_number5label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number5label3, "锅包肉32\n会员价25");
    lv_obj_set_style_text_font(ui_number5label3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number5label4 = lv_label_create(ui_number5infcontainer1);
    lv_obj_set_width(ui_number5label4, 129);
    lv_obj_set_height(ui_number5label4, 20);
    lv_obj_set_x(ui_number5label4, 3);
    lv_obj_set_y(ui_number5label4, 23);
    lv_obj_set_align(ui_number5label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number5label4, "已购买");
    lv_obj_set_style_text_font(ui_number5label4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number5ImgButtonright1 = lv_imgbtn_create(ui_number5infcontainer1);
    lv_imgbtn_set_src(ui_number5ImgButtonright1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number5ImgButtonright1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number5ImgButtonright1, 30);
    lv_obj_set_height(ui_number5ImgButtonright1, 40);
    lv_obj_set_x(ui_number5ImgButtonright1, 82);
    lv_obj_set_y(ui_number5ImgButtonright1, -16);
    lv_obj_set_align(ui_number5ImgButtonright1, LV_ALIGN_CENTER);

    ui_number4container1 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_number4container1);
    lv_obj_set_width(ui_number4container1, 200);
    lv_obj_set_height(ui_number4container1, 200);
    lv_obj_set_x(ui_number4container1, -716);
    lv_obj_set_y(ui_number4container1, -186);
    lv_obj_set_align(ui_number4container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number4container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number4Image1 = lv_img_create(ui_number4container1);
    lv_img_set_src(ui_number4Image1, &ui_img_1119412587);
    lv_obj_set_width(ui_number4Image1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number4Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number4Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number4Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number4Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number4infcontainer1 = lv_obj_create(ui_number4container1);
    lv_obj_remove_style_all(ui_number4infcontainer1);
    lv_obj_set_width(ui_number4infcontainer1, 200);
    lv_obj_set_height(ui_number4infcontainer1, 80);
    lv_obj_set_align(ui_number4infcontainer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number4infcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number4ImgButtonleft1 = lv_imgbtn_create(ui_number4infcontainer1);
    lv_imgbtn_set_src(ui_number4ImgButtonleft1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number4ImgButtonleft1, 30);
    lv_obj_set_height(ui_number4ImgButtonleft1, 40);
    lv_obj_set_x(ui_number4ImgButtonleft1, 2);
    lv_obj_set_y(ui_number4ImgButtonleft1, 4);

    ui_number4label3 = lv_label_create(ui_number4infcontainer1);
    lv_obj_set_width(ui_number4label3, 129);
    lv_obj_set_height(ui_number4label3, 50);
    lv_obj_set_x(ui_number4label3, 3);
    lv_obj_set_y(ui_number4label3, -12);
    lv_obj_set_align(ui_number4label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number4label3, "番茄牛肉46\n会员价35");
    lv_obj_set_style_text_font(ui_number4label3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number4label4 = lv_label_create(ui_number4infcontainer1);
    lv_obj_set_width(ui_number4label4, 129);
    lv_obj_set_height(ui_number4label4, 20);
    lv_obj_set_x(ui_number4label4, 3);
    lv_obj_set_y(ui_number4label4, 23);
    lv_obj_set_align(ui_number4label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number4label4, "已购买");
    lv_obj_set_style_text_font(ui_number4label4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number4ImgButtonright1 = lv_imgbtn_create(ui_number4infcontainer1);
    lv_imgbtn_set_src(ui_number4ImgButtonright1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number4ImgButtonright1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number4ImgButtonright1, 30);
    lv_obj_set_height(ui_number4ImgButtonright1, 40);
    lv_obj_set_x(ui_number4ImgButtonright1, 82);
    lv_obj_set_y(ui_number4ImgButtonright1, -16);
    lv_obj_set_align(ui_number4ImgButtonright1, LV_ALIGN_CENTER);

    ui_number3container1 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_number3container1);
    lv_obj_set_width(ui_number3container1, 200);
    lv_obj_set_height(ui_number3container1, 200);
    lv_obj_set_x(ui_number3container1, -716);
    lv_obj_set_y(ui_number3container1, -186);
    lv_obj_set_align(ui_number3container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number3container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number3Image1 = lv_img_create(ui_number3container1);
    lv_img_set_src(ui_number3Image1, &ui_img_1143013810);
    lv_obj_set_width(ui_number3Image1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number3Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number3Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number3Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number3Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number3infcontainer1 = lv_obj_create(ui_number3container1);
    lv_obj_remove_style_all(ui_number3infcontainer1);
    lv_obj_set_width(ui_number3infcontainer1, 200);
    lv_obj_set_height(ui_number3infcontainer1, 80);
    lv_obj_set_align(ui_number3infcontainer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number3infcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number3ImgButtonleft1 = lv_imgbtn_create(ui_number3infcontainer1);
    lv_imgbtn_set_src(ui_number3ImgButtonleft1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number3ImgButtonleft1, 30);
    lv_obj_set_height(ui_number3ImgButtonleft1, 40);
    lv_obj_set_x(ui_number3ImgButtonleft1, 2);
    lv_obj_set_y(ui_number3ImgButtonleft1, 4);

    ui_number3label3 = lv_label_create(ui_number3infcontainer1);
    lv_obj_set_width(ui_number3label3, 129);
    lv_obj_set_height(ui_number3label3, 50);
    lv_obj_set_x(ui_number3label3, 3);
    lv_obj_set_y(ui_number3label3, -12);
    lv_obj_set_align(ui_number3label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number3label3, "剁椒皮皮虾17\n会员价15");
    lv_obj_set_style_text_font(ui_number3label3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number3label4 = lv_label_create(ui_number3infcontainer1);
    lv_obj_set_width(ui_number3label4, 129);
    lv_obj_set_height(ui_number3label4, 20);
    lv_obj_set_x(ui_number3label4, 3);
    lv_obj_set_y(ui_number3label4, 23);
    lv_obj_set_align(ui_number3label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number3label4, "已购买");
    lv_obj_set_style_text_font(ui_number3label4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number3ImgButtonright1 = lv_imgbtn_create(ui_number3infcontainer1);
    lv_imgbtn_set_src(ui_number3ImgButtonright1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number3ImgButtonright1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number3ImgButtonright1, 30);
    lv_obj_set_height(ui_number3ImgButtonright1, 40);
    lv_obj_set_x(ui_number3ImgButtonright1, 82);
    lv_obj_set_y(ui_number3ImgButtonright1, -16);
    lv_obj_set_align(ui_number3ImgButtonright1, LV_ALIGN_CENTER);

    ui_number2container1 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_number2container1);
    lv_obj_set_width(ui_number2container1, 200);
    lv_obj_set_height(ui_number2container1, 200);
    lv_obj_set_x(ui_number2container1, -716);
    lv_obj_set_y(ui_number2container1, -186);
    lv_obj_set_align(ui_number2container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number2container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number2Image1 = lv_img_create(ui_number2container1);
    lv_img_set_src(ui_number2Image1, &ui_img_412946995);
    lv_obj_set_width(ui_number2Image1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number2Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number2Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number2Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number2Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number2infcontainer1 = lv_obj_create(ui_number2container1);
    lv_obj_remove_style_all(ui_number2infcontainer1);
    lv_obj_set_width(ui_number2infcontainer1, 200);
    lv_obj_set_height(ui_number2infcontainer1, 80);
    lv_obj_set_align(ui_number2infcontainer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number2infcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number2ImgButtonleft1 = lv_imgbtn_create(ui_number2infcontainer1);
    lv_imgbtn_set_src(ui_number2ImgButtonleft1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number2ImgButtonleft1, 30);
    lv_obj_set_height(ui_number2ImgButtonleft1, 40);
    lv_obj_set_x(ui_number2ImgButtonleft1, 2);
    lv_obj_set_y(ui_number2ImgButtonleft1, 4);

    ui_number2label3 = lv_label_create(ui_number2infcontainer1);
    lv_obj_set_width(ui_number2label3, 129);
    lv_obj_set_height(ui_number2label3, 50);
    lv_obj_set_x(ui_number2label3, 3);
    lv_obj_set_y(ui_number2label3, -12);
    lv_obj_set_align(ui_number2label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number2label3, "小炒肉17\n会员价15");
    lv_obj_set_style_text_font(ui_number2label3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number2label4 = lv_label_create(ui_number2infcontainer1);
    lv_obj_set_width(ui_number2label4, 129);
    lv_obj_set_height(ui_number2label4, 20);
    lv_obj_set_x(ui_number2label4, 3);
    lv_obj_set_y(ui_number2label4, 23);
    lv_obj_set_align(ui_number2label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number2label4, "已购买");
    lv_obj_set_style_text_font(ui_number2label4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number2ImgButtonright1 = lv_imgbtn_create(ui_number2infcontainer1);
    lv_imgbtn_set_src(ui_number2ImgButtonright1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number2ImgButtonright1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number2ImgButtonright1, 30);
    lv_obj_set_height(ui_number2ImgButtonright1, 40);
    lv_obj_set_x(ui_number2ImgButtonright1, 82);
    lv_obj_set_y(ui_number2ImgButtonright1, -16);
    lv_obj_set_align(ui_number2ImgButtonright1, LV_ALIGN_CENTER);

    ui_number1container1 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_number1container1);
    lv_obj_set_width(ui_number1container1, 200);
    lv_obj_set_height(ui_number1container1, 200);
    lv_obj_set_x(ui_number1container1, -716);
    lv_obj_set_y(ui_number1container1, -186);
    lv_obj_set_align(ui_number1container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_number1container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number1Image1 = lv_img_create(ui_number1container1);
    lv_img_set_src(ui_number1Image1, &ui_img_814352610);
    lv_obj_set_width(ui_number1Image1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_number1Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_number1Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_number1Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_number1Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number1infcontainer1 = lv_obj_create(ui_number1container1);
    lv_obj_remove_style_all(ui_number1infcontainer1);
    lv_obj_set_width(ui_number1infcontainer1, 200);
    lv_obj_set_height(ui_number1infcontainer1, 80);
    lv_obj_set_x(ui_number1infcontainer1, 0);
    lv_obj_set_y(ui_number1infcontainer1, -4);
    lv_obj_set_align(ui_number1infcontainer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_number1infcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_number1ImgButtonleft1 = lv_imgbtn_create(ui_number1infcontainer1);
    lv_imgbtn_set_src(ui_number1ImgButtonleft1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_221393495, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonleft1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number1ImgButtonleft1, 30);
    lv_obj_set_height(ui_number1ImgButtonleft1, 40);
    lv_obj_set_x(ui_number1ImgButtonleft1, 2);
    lv_obj_set_y(ui_number1ImgButtonleft1, 4);

    ui_number1label3 = lv_label_create(ui_number1infcontainer1);
    lv_obj_set_width(ui_number1label3, 129);
    lv_obj_set_height(ui_number1label3, 50);
    lv_obj_set_x(ui_number1label3, 3);
    lv_obj_set_y(ui_number1label3, -12);
    lv_obj_set_align(ui_number1label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number1label3, "白菜炖粉条17\n会员价15");
    lv_obj_set_style_text_font(ui_number1label3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number1label4 = lv_label_create(ui_number1infcontainer1);
    lv_obj_set_width(ui_number1label4, 129);
    lv_obj_set_height(ui_number1label4, 20);
    lv_obj_set_x(ui_number1label4, 3);
    lv_obj_set_y(ui_number1label4, 23);
    lv_obj_set_align(ui_number1label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number1label4, "已购买");
    lv_obj_set_style_text_font(ui_number1label4, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number1ImgButtonright1 = lv_imgbtn_create(ui_number1infcontainer1);
    lv_imgbtn_set_src(ui_number1ImgButtonright1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1284172916, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_number1ImgButtonright1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_number1ImgButtonright1, 30);
    lv_obj_set_height(ui_number1ImgButtonright1, 40);
    lv_obj_set_x(ui_number1ImgButtonright1, 82);
    lv_obj_set_y(ui_number1ImgButtonright1, -16);
    lv_obj_set_align(ui_number1ImgButtonright1, LV_ALIGN_CENTER);

    ui_Container5 = lv_obj_create(ui_orderscreen2);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 910);
    lv_obj_set_height(ui_Container5, 74);
    lv_obj_set_x(ui_Container5, 5);
    lv_obj_set_y(ui_Container5, 254);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lastpageButton2 = lv_imgbtn_create(ui_Container5);
    lv_imgbtn_set_src(ui_lastpageButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_lastpageButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lastpage_png, NULL);
    lv_imgbtn_set_src(ui_lastpageButton2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButton2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButton2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_lastpageButton2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_lastpageButton2, 60);
    lv_obj_set_height(ui_lastpageButton2, 60);
    lv_obj_set_x(ui_lastpageButton2, -100);
    lv_obj_set_y(ui_lastpageButton2, -8);
    lv_obj_set_align(ui_lastpageButton2, LV_ALIGN_CENTER);

    ui_nextpageButton1 = lv_imgbtn_create(ui_Container5);
    lv_imgbtn_set_src(ui_nextpageButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_nextpageButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_nextpage_png, NULL);
    lv_imgbtn_set_src(ui_nextpageButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_nextpageButton1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_nextpageButton1, 60);
    lv_obj_set_height(ui_nextpageButton1, 60);
    lv_obj_set_x(ui_nextpageButton1, -316);
    lv_obj_set_y(ui_nextpageButton1, 0);
    lv_obj_set_align(ui_nextpageButton1, LV_ALIGN_TOP_RIGHT);

    ui_backButton2 = lv_imgbtn_create(ui_Container5);
    lv_imgbtn_set_src(ui_backButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_backButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1609717271, NULL);
    lv_imgbtn_set_src(ui_backButton2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_backButton2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_backButton2, 50);
    lv_obj_set_height(ui_backButton2, 32);
    lv_obj_set_x(ui_backButton2, 17);
    lv_obj_set_y(ui_backButton2, 39);

    ui_confirmButton2 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_confirmButton2, 100);
    lv_obj_set_height(ui_confirmButton2, 50);
    lv_obj_set_align(ui_confirmButton2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_confirmButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_confirmButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_confirmButton2, lv_color_hex(0x99CCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confirmButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_confirmButton2, lv_color_hex(0x6699FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_confirmButton2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmLabel2 = lv_label_create(ui_confirmButton2);
    lv_obj_set_width(ui_confirmLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confirmLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_confirmLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confirmLabel2, "结账");
    lv_obj_set_style_text_color(ui_confirmLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confirmLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confirmLabel2, &ui_font_chinese30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_lastpageButton2, ui_event_lastpageButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton2, ui_event_backButton2, LV_EVENT_ALL, NULL);

}
